import { constants } from 'node:fs';
import {
  copyFile,
  lstat,
  mkdir,
  readdir,
  statfs,
  writeFile,
} from 'node:fs/promises';
import { isAbsolute, join, posix, relative, resolve, sep } from 'node:path';

import { scanWorkspace } from '@voidfall/workspace-inventory';

import { createProcessSandboxBootRunner } from './process-runner.js';
import {
  discoverForgeArgsFile,
  discoverJavaRuntime,
  readEulaAcceptance,
  type DiscoveredJava,
} from './provision.js';
import {
  SandboxError,
  type SandboxBootReport,
  type SandboxBootRunner,
  type SandboxSourceFile,
} from './types.js';

/**
 * Boots a world that has already been restored into a new private directory.
 *
 * This is deliberately separate from `Sandbox`. A normal sandbox must never
 * copy a world; a recovery rehearsal exists specifically to boot the verified
 * copy. The live workspace remains read-only, the restored directory is the
 * JVM working directory, and the generated network configuration is closed to
 * everything except loopback.
 */

const BOOTABLE_ROLES: ReadonlySet<string> = new Set([
  'mod-archive',
  'configuration',
  'datapack',
  'script',
  'runtime',
]);
const RESTORED_LEVEL_NAME = 'world';
const CONFIGURATION_HEADROOM_BYTES = 2 * 1_024 ** 3;

function toPosix(value: string): string {
  return value.split(sep).join(posix.sep);
}

function isContained(parent: string, candidate: string): boolean {
  const pathFromParent = relative(parent, candidate);
  return (
    pathFromParent.length > 0 &&
    !isAbsolute(pathFromParent) &&
    pathFromParent !== '..' &&
    !pathFromParent.startsWith(`..${sep}`)
  );
}

function validateRelativePath(value: string): readonly string[] {
  const segments = value.split('/');
  if (
    value.length === 0 ||
    segments.some((segment) => segment.length === 0 || segment === '.' || segment === '..')
  ) {
    throw new SandboxError('unsafe-path', value);
  }
  return segments;
}

async function requirePlainDirectory(path: string, errorCode: 'restored-world-missing' | 'invalid-input') {
  const entry = await lstat(path).catch(() => undefined);
  if (entry === undefined || !entry.isDirectory() || entry.isSymbolicLink()) {
    throw new SandboxError(errorCode, path);
  }
}

async function requireRestoredWorld(restoredRoot: string): Promise<void> {
  const worldRoot = join(restoredRoot, RESTORED_LEVEL_NAME);
  await requirePlainDirectory(worldRoot, 'restored-world-missing');
  const levelDat = await lstat(join(worldRoot, 'level.dat')).catch(() => undefined);
  if (levelDat === undefined || !levelDat.isFile() || levelDat.isSymbolicLink()) {
    throw new SandboxError('restored-world-missing', `${RESTORED_LEVEL_NAME}/level.dat`);
  }
}

/** Creates destination parents one segment at a time and refuses symlink hops. */
async function safeDestination(root: string, relativePath: string): Promise<string> {
  const segments = validateRelativePath(relativePath);
  let parent = root;
  for (const segment of segments.slice(0, -1)) {
    parent = join(parent, segment);
    const existing = await lstat(parent).catch(() => undefined);
    if (existing === undefined) {
      await mkdir(parent);
      continue;
    }
    if (!existing.isDirectory() || existing.isSymbolicLink()) {
      throw new SandboxError('unsafe-path', relativePath);
    }
  }
  return join(root, ...segments);
}

function renderProperties(serverPort: number): string {
  return [
    '# Generated by VoidFall for an isolated restore verification.',
    '# The active server.properties was not copied.',
    'server-ip=127.0.0.1',
    `server-port=${String(serverPort)}`,
    `level-name=${RESTORED_LEVEL_NAME}`,
    'online-mode=false',
    'max-players=0',
    'white-list=true',
    'enforce-whitelist=true',
    'enable-rcon=false',
    'enable-query=false',
    'spawn-protection=0',
    'sync-chunk-writes=false',
    '',
  ].join('\n');
}

async function listConfiguration(root: string): Promise<readonly string[]> {
  const found: string[] = [];
  const walk = async (directory: string): Promise<void> => {
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => undefined);
    if (entries === undefined) return;
    for (const entry of entries) {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) await walk(absolute);
      else if (entry.isFile()) found.push(toPosix(relative(root, absolute)));
    }
  };
  await walk(join(root, 'config'));
  await walk(join(root, RESTORED_LEVEL_NAME, 'serverconfig'));
  return found.sort((left, right) => left.localeCompare(right, 'en-US'));
}

export interface RestoredWorldBootEvidence {
  readonly java: DiscoveredJava;
  readonly argsFile: string;
  readonly filesCopied: number;
  readonly bytesCopied: number;
  readonly report: SandboxBootReport;
}

export interface RunRestoredWorldBootOptions {
  /** Read-only linked server runtime. */
  readonly workspaceRoot: string;
  /** Active world path, used only to exclude it from the runtime copy. */
  readonly activeWorldRoot: string;
  /** Newly materialised restore target. It is never the active server root. */
  readonly restoredRoot: string;
  readonly timeoutMs?: number;
  readonly serverPort?: number;
  readonly maximumMemoryMiB?: number;
  readonly onProgress?: (message: string) => void;
  /** Test seams; production callers rely on discovery and the process runner. */
  readonly java?: DiscoveredJava;
  readonly argsFile?: string;
  readonly runner?: SandboxBootRunner;
}

export async function runRestoredWorldBoot(
  options: RunRestoredWorldBootOptions,
): Promise<RestoredWorldBootEvidence> {
  if (
    options === null ||
    typeof options !== 'object' ||
    !isAbsolute(options.workspaceRoot) ||
    !isAbsolute(options.activeWorldRoot) ||
    !isAbsolute(options.restoredRoot)
  ) {
    throw new SandboxError('invalid-input');
  }
  const workspaceRoot = resolve(options.workspaceRoot);
  const activeWorldRoot = resolve(options.activeWorldRoot);
  const restoredRoot = resolve(options.restoredRoot);
  if (
    restoredRoot === workspaceRoot ||
    isContained(workspaceRoot, restoredRoot) ||
    isContained(restoredRoot, workspaceRoot)
  ) {
    throw new SandboxError('restore-root-overlaps-workspace', restoredRoot);
  }
  if (!isContained(workspaceRoot, activeWorldRoot)) {
    throw new SandboxError('invalid-input', activeWorldRoot);
  }
  await requirePlainDirectory(workspaceRoot, 'invalid-input');
  await requirePlainDirectory(restoredRoot, 'invalid-input');
  await requireRestoredWorld(restoredRoot);
  if (!(await readEulaAcceptance(workspaceRoot))) {
    throw new SandboxError('eula-not-accepted-in-workspace', workspaceRoot);
  }

  const progress = options.onProgress ?? ((): void => undefined);
  const java = options.java ?? (await discoverJavaRuntime());
  const argsFile = options.argsFile ?? (await discoverForgeArgsFile(workspaceRoot));
  const scan = await scanWorkspace({ root: workspaceRoot, includeRuntime: true });
  const activeWorldPath = toPosix(relative(workspaceRoot, activeWorldRoot));
  const files: SandboxSourceFile[] = scan.files
    .filter((file) => BOOTABLE_ROLES.has(file.role))
    .filter(
      (file) =>
        file.path !== 'server.properties' &&
        file.path !== 'eula.txt' &&
        file.path !== activeWorldPath &&
        !file.path.startsWith(`${activeWorldPath}/`),
    )
    .map((file) => ({ path: file.path, role: file.role as SandboxSourceFile['role'] }));
  const bytesCopied = files.reduce((total, file) => {
    const inventoried = scan.files.find((entry) => entry.path === file.path);
    return total + (inventoried?.sizeBytes ?? 0);
  }, 0);
  const available = await statfs(restoredRoot).catch(() => undefined);
  if (available !== undefined) {
    const free = Number(available.bavail) * Number(available.bsize);
    if (Number.isFinite(free) && free < bytesCopied + CONFIGURATION_HEADROOM_BYTES) {
      throw new SandboxError('insufficient-space', `${String(Math.round(free / 1_048_576))} MiB free`);
    }
  }
  progress(`${String(files.length)} runtime file(s) to copy.`);

  for (const file of files) {
    const first = validateRelativePath(file.path)[0];
    if (first === RESTORED_LEVEL_NAME) {
      throw new SandboxError('unsafe-path', file.path);
    }
    const source = join(workspaceRoot, ...file.path.split('/'));
    const destination = await safeDestination(restoredRoot, file.path);
    try {
      await copyFile(source, destination, constants.COPYFILE_EXCL);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
        throw new SandboxError('destination-conflict', file.path);
      }
      throw new SandboxError('source-missing', file.path);
    }
  }

  const serverPort = options.serverPort ?? 25_998;
  if (!Number.isInteger(serverPort) || serverPort < 1024 || serverPort > 65_535) {
    throw new SandboxError('invalid-input');
  }
  await writeFile(join(restoredRoot, 'server.properties'), renderProperties(serverPort), {
    encoding: 'utf8',
    flag: 'wx',
  });
  await writeFile(
    join(restoredRoot, 'eula.txt'),
    '# Accepted by the operator for this isolated restore verification.\neula=true\n',
    { encoding: 'utf8', flag: 'wx' },
  );

  const runner =
    options.runner ??
    createProcessSandboxBootRunner({
      javaExecutable: java.executable,
      launch: { kind: 'forge-args-file', argsFile },
      initialMemoryMiB: 1_024,
      maximumMemoryMiB: options.maximumMemoryMiB ?? 4_096,
    });
  const configurationBefore = new Set(await listConfiguration(restoredRoot));
  const startedAt = Date.now();
  const result = await runner.boot({
    sandboxRoot: restoredRoot,
    timeoutMs: options.timeoutMs ?? 600_000,
  });
  const configurationAfter = await listConfiguration(restoredRoot);
  const report: SandboxBootReport = Object.freeze({
    outcome: result.outcome,
    durationMs: Date.now() - startedAt,
    generatedFiles: Object.freeze(
      configurationAfter.filter((path) => !configurationBefore.has(path)),
    ),
    tail: Object.freeze([...result.tail]),
  });
  return Object.freeze({ java, argsFile, filesCopied: files.length, bytesCopied, report });
}
