import { copyFile, mkdir, mkdtemp, readdir, rm, writeFile } from 'node:fs/promises';
import { isAbsolute, join, posix, relative, resolve, sep } from 'node:path';

import {
  SandboxError,
  type ComposeSandboxInput,
  type SandboxBootReport,
  type SandboxBootRunner,
  type SandboxServerProperties,
} from './types.js';

/**
 * Builds a sandbox, boots it, and deletes it.
 *
 * The composition is the safety-critical part and is therefore the part with
 * the most refusals in it. Everything the sandbox contains was named by the
 * caller; nothing is discovered, inferred or brought along for convenience.
 */

/** Where a boot writes files a mod generates on first run. */
const CONFIG_ROOT = 'config';

/**
 * Windows' extended-length path prefix, built from code points.
 *
 * Written this way because the literal is four characters of which three are
 * backslashes, and a run of backslashes is exactly what gets mangled passing
 * through tooling — quietly, into a string that still compiles.
 */
const WINDOWS_EXTENDED_PREFIX = String.fromCharCode(92, 92, 63, 92);

/**
 * Removal that survives Windows.
 *
 * Two things go wrong there and both were observed on the first real boot.
 * Handles are released asynchronously after a process dies, so a delete issued
 * immediately after a kill fails with `EBUSY`; and a sandbox composed from a
 * deeply nested source produces paths past `MAX_PATH`, which the ordinary APIs
 * cannot even name — the message is "cannot find part of the path" for a file
 * that is plainly there.
 *
 * The extended-length prefix fixes the second. Retrying fixes the first. A
 * sandbox that cannot be deleted is not disposable, which is most of what it
 * claimed to be.
 */
async function removeTree(root: string): Promise<void> {
  const target = process.platform === 'win32' ? `${WINDOWS_EXTENDED_PREFIX}${root}` : root;
  let lastError: unknown;
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      await rm(target, { recursive: true, force: true });
      return;
    } catch (error) {
      lastError = error;
      await new Promise((resolve) => setTimeout(resolve, 250 * (attempt + 1)));
    }
  }
  throw lastError;
}

function toPosix(value: string): string {
  return value.split(sep).join(posix.sep);
}

/** Refuses anything that would land outside the root it was resolved against. */
function resolveInside(root: string, relativePath: string): string {
  const segments = relativePath.split('/');
  if (
    relativePath.length === 0 ||
    segments.some((segment) => segment === '' || segment === '.' || segment === '..')
  ) {
    throw new SandboxError('unsafe-path', relativePath);
  }
  return join(root, ...segments);
}

function renderServerProperties(properties: SandboxServerProperties): string {
  // Written as a fixed, minimal set. Copying the operator's file would bring
  // their port, their seed and their RCON password into a throwaway directory.
  return [
    '# Generated by VoidFall for a disposable sandbox boot.',
    '# Not derived from any real server.properties.',
    `server-ip=${properties.serverIp}`,
    `server-port=${String(properties.serverPort)}`,
    `level-name=${properties.levelName}`,
    `online-mode=${String(properties.onlineMode)}`,
    // A sandbox that let somebody in would be a server, not a test.
    'max-players=0',
    'white-list=true',
    'enforce-whitelist=true',
    'enable-rcon=false',
    'enable-query=false',
    'spawn-protection=0',
    'sync-chunk-writes=false',
    '',
  ].join('\n');
}

export interface SandboxOptions {
  /** Sandboxes are created under here, and nowhere else. */
  readonly parentDirectory: string;
  readonly runner: SandboxBootRunner;
  readonly clock?: () => number;
}

export interface ComposedSandbox {
  readonly root: string;
  readonly levelName: string;
  /** Configuration files present before any boot, for the generated-file diff. */
  readonly configurationBefore: readonly string[];
}

export class Sandbox {
  readonly #parentDirectory: string;
  readonly #runner: SandboxBootRunner;
  readonly #clock: () => number;
  #composed: ComposedSandbox | undefined;

  public constructor(options: SandboxOptions) {
    if (
      options === null ||
      typeof options !== 'object' ||
      !isAbsolute(options.parentDirectory) ||
      typeof options.runner?.boot !== 'function'
    ) {
      throw new SandboxError('invalid-input');
    }
    this.#parentDirectory = options.parentDirectory;
    this.#runner = options.runner;
    this.#clock = options.clock ?? ((): number => Date.now());
  }

  public get root(): string | undefined {
    return this.#composed?.root;
  }

  /**
   * Builds the sandbox from exactly what was named.
   *
   * The world is conspicuously absent, and its absence is the point: a fresh
   * level name is written into the generated properties, so the server creates
   * an empty world inside the sandbox and never looks for anybody's.
   */
  public async compose(input: ComposeSandboxInput): Promise<ComposedSandbox> {
    if (input === null || typeof input !== 'object' || !isAbsolute(input.workspaceRoot)) {
      throw new SandboxError('invalid-input');
    }
    if (input.eulaAccepted !== true) {
      // No default, and no inference from "they asked for a boot". Accepting a
      // licence agreement on somebody's behalf is not a convenience.
      throw new SandboxError('eula-not-accepted');
    }
    if (!Number.isInteger(input.serverPort) || input.serverPort < 1024 || input.serverPort > 65_535) {
      throw new SandboxError('invalid-input');
    }

    const root = await mkdtemp(join(this.#parentDirectory, 'voidfall-sandbox-'));
    // A sandbox inside the workspace would be scanned by the next import, and
    // deleting it would delete part of what it was copied from.
    const inside = relative(resolve(input.workspaceRoot), resolve(root));
    if (inside !== '' && !inside.startsWith('..') && !isAbsolute(inside)) {
      await rm(root, { recursive: true, force: true });
      throw new SandboxError('sandbox-root-inside-workspace');
    }

    const staged = input.stagedFiles ?? new Map<string, string>();
    for (const file of input.files) {
      const target = resolveInside(root, file.path);
      await mkdir(join(target, '..'), { recursive: true });
      const stagedContent = staged.get(file.path);
      if (stagedContent !== undefined) {
        // The whole reason to boot: test the change, not what is installed.
        await writeFile(target, stagedContent, 'utf8');
        continue;
      }
      const source = resolveInside(input.workspaceRoot, file.path);
      try {
        await copyFile(source, target);
      } catch {
        throw new SandboxError('source-missing', file.path);
      }
    }

    const levelName = 'voidfall-sandbox-world';
    await writeFile(
      join(root, 'server.properties'),
      renderServerProperties({
        serverIp: '127.0.0.1',
        serverPort: input.serverPort,
        levelName,
        onlineMode: false,
      }),
      'utf8',
    );
    await writeFile(
      join(root, 'eula.txt'),
      '# Accepted by the operator for this disposable sandbox boot.\neula=true\n',
      'utf8',
    );

    const composed: ComposedSandbox = Object.freeze({
      root,
      levelName,
      configurationBefore: await listConfiguration(root),
    });
    this.#composed = composed;
    return composed;
  }

  /**
   * Boots the sandbox and reports what happened, including what it wrote.
   *
   * `timed-out` is reported as its own outcome rather than folded into a
   * failure. The server may simply have been slow; saying it did not finish
   * inside the window is a fact, and saying it failed would not be.
   */
  public async boot(options: { readonly timeoutMs: number } = { timeoutMs: 300_000 }): Promise<SandboxBootReport> {
    const composed = this.#composed;
    if (composed === undefined) throw new SandboxError('not-composed');

    const startedAt = this.#clock();
    const result = await this.#runner.boot({
      sandboxRoot: composed.root,
      timeoutMs: options.timeoutMs,
    });
    const durationMs = this.#clock() - startedAt;

    const after = await listConfiguration(composed.root);
    const before = new Set(composed.configurationBefore);
    const generatedFiles = after.filter((path) => !before.has(path));

    return Object.freeze({
      outcome: result.outcome,
      durationMs,
      generatedFiles: Object.freeze(generatedFiles),
      tail: Object.freeze([...result.tail]),
    });
  }

  /**
   * Deletes the sandbox.
   *
   * Safe to call twice, and safe to call on a sandbox that never composed —
   * cleanup that throws when there is nothing to clean is cleanup people stop
   * calling.
   */
  public async dispose(): Promise<void> {
    const composed = this.#composed;
    this.#composed = undefined;
    if (composed === undefined) return;
    await removeTree(composed.root);
  }
}

/** Lists the configuration tree, sorted, relative to the sandbox root. */
async function listConfiguration(root: string): Promise<readonly string[]> {
  const found: string[] = [];
  const walk = async (directory: string): Promise<void> => {
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => undefined);
    if (entries === undefined) return;
    for (const entry of entries) {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) {
        await walk(absolute);
        continue;
      }
      if (entry.isFile()) found.push(toPosix(relative(root, absolute)));
    }
  };
  await walk(join(root, CONFIG_ROOT));
  found.sort((left, right) => left.localeCompare(right, 'en-US'));
  return found;
}
