import { createPublicKey, randomUUID } from 'node:crypto';
import type { TLSSocket } from 'node:tls';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import { Type, type Static } from '@sinclair/typebox';
import {
  computeAgentPayloadHash,
  createOpaqueToken,
  hashPassword,
  hashOpaqueToken,
  isAgentEnvelopeFresh,
  safeEqualHex,
  sha256Hex,
  verifyAgentEnvelopeSignature,
  verifyPassword,
} from '@voidfall/authentication';
import {
  AgentEnvelopeSchema,
  SemanticVersionSchema,
  validateAgentEnvelope,
  validateAgentHeartbeatPayload,
  type ActorRef,
  type AgentEnvelope,
  type AuditEvent,
  type ResourceRef,
} from '@voidfall/contracts';
import {
  createRepositories,
  ServerRuntimeBindingError,
  type Database,
  type Repositories,
} from '@voidfall/database';
import {
  hasPermission,
  type PanelPermission,
} from '@voidfall/permissions';
import Fastify, {
  type FastifyInstance,
  type FastifyReply,
  type FastifyRequest,
} from 'fastify';
import {
  registerArtifactRoutes,
  type ArtifactPermission,
  type ArtifactQuarantineStore,
} from './artifact-routes.js';
import { registerAgentWorkRoutes } from './agent-work-routes.js';
import { registerProcessRoutes, type ProcessPermission } from './process-routes.js';
import {
  registerWorkspaceRoutes,
  type ReleaseBuilder,
  type SandboxLauncher,
  type WorkspaceConfigurationService,
  type WorkspaceEcosystemService,
  type WorkspacePermission,
  type WorkspaceScanner,
} from './workspace-routes.js';
import {
  registerOperationalRoutes,
  type OperationalPermission,
} from './operational-routes.js';
import {
  registerConfigurationRoutes,
  type ConfigurationPermission,
  type ConfigurationValueReader,
} from './configuration-routes.js';
import {
  registerAuthorizedFileRoutes,
  type AuthorizedFilePermission,
} from './authorized-file-routes.js';
import type { AuthorizedFileService } from '@voidfall/authorized-files';
import { registerBackupRoutes, type BackupPermission } from './backup-routes.js';
import { registerTelemetryRoutes, type TelemetryPermission } from './telemetry-routes.js';
import { registerScheduleRoutes, type SchedulePermission } from './schedule-routes.js';
import { registerLocalSession } from './local-session.js';
import { registerStaticPanel } from './static-panel.js';
import {
  registerDatapackLoadOrderRoutes,
  type DatapackLoadOrderPermission,
} from './datapack-load-order-routes.js';

const SESSION_COOKIE = 'voidfall_session';
const ABSOLUTE_SESSION_MS = 12 * 60 * 60_000;
const IDLE_SESSION_MS = 30 * 60_000;

interface AuthContext {
  readonly sessionId: string;
  readonly csrfTokenHash: string;
  /** The token as issued. `null` only for sessions created before 0017. */
  readonly csrfToken: string | null;
  readonly user: {
    readonly id: string;
    readonly email: string;
    readonly displayName: string;
  };
  readonly permissions: readonly PanelPermission[];
}

declare module 'fastify' {
  interface FastifyRequest {
    correlationId: string;
    authContext?: AuthContext;
  }
}

class ApiError extends Error {
  constructor(
    readonly statusCode: number,
    readonly code: string,
    message: string,
  ) {
    super(message);
  }
}

export type AgentTransportVerifier = (
  request: FastifyRequest,
  expectedCertificateFingerprint: string,
) => boolean | Promise<boolean>;

export type LocalOperatorBootstrap =
  | {
      readonly mode: 'development';
      readonly email: string;
    }
  | {
      readonly mode: 'desktop';
      readonly email: string;
      /** Per-process navigation credential generated by the desktop host. */
      readonly launchToken: string;
    };

export interface BuildControlApiOptions {
  readonly database: Database;
  readonly clock?: () => Date;
  readonly cookieSecure?: boolean;
  readonly logger?: boolean;
  readonly agentTransportVerifier?: AgentTransportVerifier;
  /**
   * Authorized typed reader for configuration values. It is optional and
   * deny-by-default: without it the API reports values as unavailable rather
   * than caching, guessing or persisting them.
   */
  readonly configurationReader?: ConfigurationValueReader;
  /**
   * Store that receives an uploaded artifact as a stream. It is optional and
   * deny-by-default: without it an upload is refused rather than accepted into
   * a location nobody configured.
   */
  readonly artifactQuarantineStore?: ArtifactQuarantineStore;
  /**
   * Service holding the authorized file roots. It is optional and
   * deny-by-default: without it the file routes report themselves unavailable
   * rather than falling back to a root nobody declared.
   */
  readonly authorizedFiles?: AuthorizedFileService;
  /**
   * Whether an approved in-game metrics provider is connected. Absent means no,
   * and the metrics route reports tick timing as unavailable rather than
   * leaving the panel to draw a number nobody measured.
   */
  readonly gameProviderConnected?: boolean;
  /**
   * Reads an imported workspace. Optional and deny-by-default: without it the
   * workspace routes report themselves unavailable rather than scanning a
   * directory nobody wired a scanner for.
   */
  readonly workspaceScanner?: WorkspaceScanner;
  /** Normalizes and persists semantic ecosystem analysis for an inventory. */
  readonly workspaceEcosystem?: WorkspaceEcosystemService;
  /** Which roots may be registered. Operator policy, never a route's guess. */
  readonly workspaceRootPolicy?: (
    rootPath: string,
  ) => Promise<{ readonly rootPath: string } | { readonly refusal: string }>;
  /**
   * Absolute path of the exported panel, served from this same origin.
   *
   * Optional: without it the API answers only its own routes, which is the
   * shape a deployment behind a proxy wants. With it, panel and API share an
   * origin by construction and the session cookie's `SameSite=strict` keeps
   * working with nothing to configure.
   */
  readonly panelExportRoot?: string;
  /**
   * Reads, validates and stages a workspace's configuration. Optional and
   * deny-by-default: without it those routes report themselves unavailable
   * rather than staging into a directory nobody chose.
   */
  readonly workspaceConfiguration?: WorkspaceConfigurationService;
  /**
   * Starts a disposable sandbox boot. Optional and deny-by-default: without it
   * the sandbox routes report themselves unavailable rather than accepting a
   * run that nothing will ever execute.
   */
  readonly sandboxLauncher?: SandboxLauncher;
  /**
   * Sign in the local operator without a password.
   *
   * Only the terminal-local and desktop hosts set this. The route refuses
   * anything that did not arrive on loopback; desktop additionally requires a
   * per-process launch token. Authentication is deferred, not removed: the
   * session, cookie, CSRF token and every permission check are exactly the ones
   * the real login produces.
   */
  readonly localOperator?: LocalOperatorBootstrap;
  /** Where a signed-out visitor lands. Defaults to the sign-in screen. */
  readonly panelEntryPath?: string;
  /**
   * Plans and produces a release. Optional and deny-by-default: without it
   * those routes report themselves unavailable rather than promising an
   * artefact that nothing will produce.
   */
  readonly releaseBuilder?: ReleaseBuilder;
  /**
   * Reads a directory and works out how the server there starts.
   *
   * Optional and deny-by-default. Returns the canonical directory alongside
   * the descriptor rather than approving what it was given — the same contract
   * the workspace root policy settled on, for the same reason.
   */
  readonly serverRuntimeDetector?: (rootPath: string) => Promise<
    | {
        readonly rootPath: string;
        readonly runtime: {
          readonly family: string;
          readonly shape: string;
          readonly entry: string;
          readonly evidence: string;
        };
      }
    | { readonly refusal: string }
  >;
}

function requestCorrelationId(request: FastifyRequest): string {
  const supplied = request.headers['x-correlation-id'];
  return typeof supplied === 'string' && /^[0-9a-f-]{36}$/iu.test(supplied)
    ? supplied
    : randomUUID();
}

function anonymizeIp(ipAddress: string): string {
  if (/^\d{1,3}(?:\.\d{1,3}){3}$/u.test(ipAddress)) {
    const parts = ipAddress.split('.');
    return `${parts[0]}.${parts[1]}.${parts[2]}.0/24`;
  }
  const groups = ipAddress.split(':').filter(Boolean).slice(0, 4);
  return `${groups.join(':')}::/64`;
}

function normalizedFingerprint(value: string): string {
  return value.replaceAll(':', '').toLocaleLowerCase('en-US');
}

function defaultAgentTransportVerifier(
  request: FastifyRequest,
  expectedCertificateFingerprint: string,
): boolean {
  const socket = request.raw.socket as TLSSocket;
  if (socket.authorized !== true || typeof socket.getPeerCertificate !== 'function') return false;
  const certificate = socket.getPeerCertificate();
  const presented = certificate.fingerprint256;
  return (
    typeof presented === 'string' &&
    safeEqualHex(normalizedFingerprint(presented), expectedCertificateFingerprint)
  );
}

function auditEvent(input: {
  readonly request: FastifyRequest;
  readonly now: Date;
  readonly actor: ActorRef;
  readonly action: string;
  readonly resource: ResourceRef;
  readonly outcome: AuditEvent['outcome'];
  readonly reason?: string;
}): AuditEvent {
  return {
    schemaVersion: 1,
    id: randomUUID(),
    occurredAt: input.now.toISOString(),
    correlationId: input.request.correlationId,
    actor: input.actor,
    source: 'api',
    action: input.action,
    resource: input.resource,
    outcome: input.outcome,
    ...(input.reason === undefined ? {} : { reason: input.reason }),
  };
}

function setSessionCookie(reply: FastifyReply, token: string, secure: boolean, expiresAt: Date): void {
  reply.setCookie(SESSION_COOKIE, token, {
    path: '/',
    httpOnly: true,
    secure,
    sameSite: 'strict',
    expires: expiresAt,
  });
}

function clearSessionCookie(reply: FastifyReply, secure: boolean): void {
  reply.clearCookie(SESSION_COOKIE, {
    path: '/',
    httpOnly: true,
    secure,
    sameSite: 'strict',
  });
}

const LoginBodySchema = Type.Object(
  {
    email: Type.String({ format: 'email', maxLength: 320 }),
    password: Type.String({ minLength: 1, maxLength: 1_024 }),
  },
  { additionalProperties: false },
);
type LoginBody = Static<typeof LoginBodySchema>;

const CreateServerBodySchema = Type.Object(
  {
    slug: Type.String({ pattern: '^[a-z0-9][a-z0-9-]{0,62}$' }),
    displayName: Type.String({ minLength: 1, maxLength: 120 }),
    environment: Type.Union([
      Type.Literal('local'),
      Type.Literal('test'),
      Type.Literal('staging'),
      Type.Literal('production'),
    ]),
    minecraftVersion: Type.String({ minLength: 1, maxLength: 32 }),
    loader: Type.String({ minLength: 1, maxLength: 32 }),
    loaderVersion: Type.String({ minLength: 1, maxLength: 32 }),
    maxPlayers: Type.Integer({ minimum: 1, maximum: 1_000 }),
  },
  { additionalProperties: false },
);
type CreateServerBody = Static<typeof CreateServerBodySchema>;

const SetServerRuntimeSchema = Type.Union([
  Type.Object(
    {
      /** An unregistered directory, accepted once and never returned. */
      rootPath: Type.String({ minLength: 2, maxLength: 4_096 }),
    },
    { additionalProperties: false },
  ),
  Type.Object(
    {
      /** A registered server workspace whose root already lives on the host. */
      workspaceId: Type.String({ format: 'uuid' }),
    },
    { additionalProperties: false },
  ),
]);
type SetServerRuntimeBody = Static<typeof SetServerRuntimeSchema>;

const AgentRegistrationBodySchema = Type.Object(
  {
    provisioningToken: Type.String({ minLength: 43, maxLength: 256, pattern: '^[A-Za-z0-9_-]+$' }),
    agentId: Type.String({ format: 'uuid' }),
    serverInstanceId: Type.String({ format: 'uuid' }),
    publicKeyPem: Type.String({ minLength: 64, maxLength: 4_096, pattern: '^-----BEGIN PUBLIC KEY-----' }),
    certificateFingerprint: Type.String({ pattern: '^[a-f0-9]{64}$' }),
    softwareVersion: SemanticVersionSchema,
    // Closed capability list. A capability is a named, reviewed operation; it
    // never authorizes a generic executor.
    capabilities: Type.Array(
      Type.Union([
        Type.Literal('heartbeat'),
        Type.Literal('configuration.apply'),
        Type.Literal('artifact.install'),
        Type.Literal('backup.create'),
        Type.Literal('backup.verify-restore'),
        Type.Literal('datapack-load-order.observe'),
      ]),
      { minItems: 1, maxItems: 6, uniqueItems: true },
    ),
  },
  { additionalProperties: false },
);
type AgentRegistrationBody = Static<typeof AgentRegistrationBodySchema>;

export async function buildControlApi(options: BuildControlApiOptions): Promise<FastifyInstance> {
  const clock = options.clock ?? (() => new Date());
  const cookieSecure = options.cookieSecure ?? true;
  const verifyAgentTransport = options.agentTransportVerifier ?? defaultAgentTransportVerifier;
  const repositories = createRepositories(options.database);
  // Keep the password verification path equivalent even when the account does not exist.
  const dummyPasswordHash = await hashPassword('voidfall-control-api-dummy-password');
  const app = Fastify({
    logger: options.logger ?? false,
    bodyLimit: 1024 * 1024,
    requestIdHeader: false,
    ajv: { customOptions: { allErrors: true, removeAdditional: false, coerceTypes: false } },
  });

  await app.register(cookie);
  await app.register(helmet, {
    contentSecurityPolicy: false,
    crossOriginResourcePolicy: { policy: 'same-site' },
  });
  await app.register(rateLimit, { global: false, max: 100, timeWindow: '1 minute' });

  /**
   * An empty JSON body means "no body", not "invalid request".
   *
   * Triggering an action with `POST` and nothing to say is ordinary — running
   * a scan, revoking a session — and a client that sets a JSON content type
   * anyway is doing something normal too. The default parser answered those
   * with a validation error whose `details` were empty, which is the worst
   * kind of refusal: correct, and impossible to act on.
   *
   * Routes that need a body are unaffected. Their schema still rejects a
   * missing one, and now with a message that names the field.
   */
  app.addContentTypeParser(
    'application/json',
    { parseAs: 'string' },
    (_request, body: string, done) => {
      if (body === '') {
        done(null, undefined);
        return;
      }
      try {
        done(null, JSON.parse(body));
      } catch (error) {
        done(error instanceof Error ? error : new Error('invalid json'), undefined);
      }
    },
  );

  app.addHook('onRequest', async (request, reply) => {
    request.correlationId = requestCorrelationId(request);
    reply.header('x-correlation-id', request.correlationId);
  });

  app.setErrorHandler((error, request, reply) => {
    const frameworkStatusCode =
      typeof error === 'object' &&
      error !== null &&
      'statusCode' in error &&
      typeof error.statusCode === 'number'
        ? error.statusCode
        : 500;
    const statusCode = error instanceof ApiError ? error.statusCode : frameworkStatusCode;
    const code =
      error instanceof ApiError
        ? error.code
        : statusCode === 400
          ? 'VALIDATION_ERROR'
          : 'INTERNAL_ERROR';
    const message =
      statusCode >= 500
        ? 'A operação não pôde ser concluída.'
        : error instanceof ApiError
          ? error.message
          : 'A solicitação é inválida.';
    if (statusCode >= 500) {
      // Logged, because a 500 whose cause never appears anywhere is
      // undiagnosable — and that is not hypothetical: an agent claim failed
      // with 500 on every attempt here, and the only way to see why was to
      // read the code path by hand. The body a caller receives is unchanged;
      // the detail goes to the server's own log, where a host detail belongs.
      request.log.error({ err: error, correlationId: request.correlationId }, 'request failed');
    }
    void reply.code(statusCode).send({
      error: { code, message, correlationId: request.correlationId, details: [] },
    });
  });

  async function authenticate(request: FastifyRequest): Promise<void> {
    const rawToken = request.cookies[SESSION_COOKIE];
    if (rawToken === undefined) throw new ApiError(401, 'AUTH_REQUIRED', 'Autenticação necessária.');
    const now = clock();
    const session = await repositories.sessions.findActive(hashOpaqueToken(rawToken), now);
    if (session === undefined) throw new ApiError(401, 'SESSION_INVALID', 'Sessão inválida ou expirada.');
    const permissions = await repositories.permissions.forUser(session.userId);
    request.authContext = {
      sessionId: session.id,
      csrfTokenHash: session.csrfTokenHash,
      csrfToken: session.csrfToken,
      user: {
        id: session.user.id,
        email: session.user.emailNormalized,
        displayName: session.user.displayName,
      },
      permissions,
    };
    await repositories.sessions.touch(
      session.id,
      now,
      new Date(Math.min(Date.parse(session.expiresAt), now.getTime() + IDLE_SESSION_MS)),
    );
  }

  function requirePermission(permission: PanelPermission) {
    return async (request: FastifyRequest): Promise<void> => {
      const auth = request.authContext;
      if (auth === undefined) throw new ApiError(401, 'AUTH_REQUIRED', 'Autenticação necessária.');
      if (hasPermission(auth.permissions, permission)) return;
      await repositories.audit.append(
        auditEvent({
          request,
          now: clock(),
          actor: { type: 'panel-user', id: auth.user.id },
          action: 'authorization.denied',
          resource: { type: 'permission', id: permission },
          outcome: 'denied',
          reason: 'deny-by-default RBAC policy',
        }),
      );
      throw new ApiError(403, 'PERMISSION_DENIED', 'Permissão insuficiente.');
    };
  }

  async function requireCsrf(request: FastifyRequest): Promise<void> {
    const auth = request.authContext;
    if (auth === undefined) throw new ApiError(401, 'AUTH_REQUIRED', 'Autenticação necessária.');
    const csrfToken = request.headers['x-csrf-token'];
    if (
      typeof csrfToken !== 'string' ||
      !safeEqualHex(hashOpaqueToken(csrfToken), auth.csrfTokenHash)
    ) {
      throw new ApiError(403, 'CSRF_INVALID', 'Token CSRF ausente ou inválido.');
    }
  }

  app.get('/health/live', async () => ({ status: 'ok', service: 'control-api' }));
  app.get('/health/ready', async () => {
    await options.database.query('SELECT 1 AS ready');
    return { status: 'ready', dependencies: { database: 'available' } };
  });

  app.post<{ Body: LoginBody }>(
    '/api/v1/auth/login',
    {
      schema: { body: LoginBodySchema },
      config: { rateLimit: { max: 5, timeWindow: '1 minute' } },
    },
    async (request, reply) => {
      const now = clock();
      const user = await repositories.users.findByEmail(request.body.email);
      const passwordValid = await verifyPassword(
        user?.passwordHash ?? dummyPasswordHash,
        request.body.password,
      );
      const locked =
        user !== undefined &&
        (user.status === 'disabled' ||
          (user.lockedUntil !== undefined && Date.parse(user.lockedUntil) > now.getTime()));
      if (user === undefined || !passwordValid || locked) {
        if (user !== undefined && !locked) await repositories.users.recordFailedLogin(user.id, now);
        await repositories.audit.append(
          auditEvent({
            request,
            now,
            actor: { type: 'system', id: 'anonymous' },
            action: 'auth.login',
            resource: { type: 'panel-session', id: 'new' },
            outcome: 'denied',
            reason: 'invalid credentials or locked account',
          }),
        );
        throw new ApiError(401, 'INVALID_CREDENTIALS', 'Credenciais inválidas.');
      }
      await repositories.users.recordSuccessfulLogin(user.id, now);
      const sessionToken = createOpaqueToken();
      const csrfToken = createOpaqueToken();
      const expiresAt = new Date(now.getTime() + ABSOLUTE_SESSION_MS);
      await repositories.sessions.create({
        userId: user.id,
        tokenHash: hashOpaqueToken(sessionToken),
        csrfTokenHash: hashOpaqueToken(csrfToken),
        // Stored as issued as well, so a reloaded page can present it again.
        // The session token stays hashed — that one is the credential.
        csrfToken,
        now,
        expiresAt,
        idleExpiresAt: new Date(now.getTime() + IDLE_SESSION_MS),
        ipPrefix: anonymizeIp(request.ip),
        ...(request.headers['user-agent'] === undefined
          ? {}
          : { userAgentHash: sha256Hex(request.headers['user-agent']) }),
      });
      setSessionCookie(reply, sessionToken, cookieSecure, expiresAt);
      await repositories.audit.append(
        auditEvent({
          request,
          now,
          actor: { type: 'panel-user', id: user.id },
          action: 'auth.login',
          resource: { type: 'panel-session', id: 'current' },
          outcome: 'succeeded',
        }),
      );
      return {
        user: { id: user.id, email: user.emailNormalized, displayName: user.displayName },
        csrfToken,
        expiresAt: expiresAt.toISOString(),
      };
    },
  );

  app.get(
    '/api/v1/auth/session',
    { preHandler: [authenticate] },
    async (request) => ({
      user: request.authContext?.user,
      permissions: request.authContext?.permissions ?? [],
      // Without this a reloaded screen holds a valid cookie and still cannot
      // write: the CSRF token existed only in the login response, so every
      // mutation after a refresh failed. Returning it here is safe — the
      // endpoint is authenticated and same-origin, and the token means nothing
      // without the cookie that has to travel with it.
      csrfToken: request.authContext?.csrfToken ?? null,
    }),
  );

  app.post(
    '/api/v1/auth/logout',
    { preHandler: [authenticate, requireCsrf] },
    async (request, reply) => {
      const auth = request.authContext;
      if (auth === undefined) throw new ApiError(401, 'AUTH_REQUIRED', 'Autenticação necessária.');
      const now = clock();
      await repositories.sessions.revoke(auth.sessionId, now);
      clearSessionCookie(reply, cookieSecure);
      await repositories.audit.append(
        auditEvent({
          request,
          now,
          actor: { type: 'panel-user', id: auth.user.id },
          action: 'auth.logout',
          resource: { type: 'panel-session', id: auth.sessionId },
          outcome: 'succeeded',
        }),
      );
      return reply.code(204).send();
    },
  );

  app.get(
    '/api/v1/servers',
    { preHandler: [authenticate, requirePermission('server.view')] },
    async () => ({
      dataQuality: 'stored',
      // Mapped rather than returned whole. Adding `run_directory` to the row
      // put a host path straight into this listing, which is exactly the leak
      // the workspace routes have been guarded against since the first slice —
      // and it arrived through a column, not through a new endpoint.
      servers: await Promise.all(
        (await repositories.servers.list()).map(async (server) => {
          /**
           * The observation, read from where it is actually written.
           *
           * `server_instances.observed_state` is a Phase 1 column that nothing
           * has ever written, so a running server reported `unavailable`
           * forever. The agent records into `server_process_states`, which
           * also carries who observed it, when, and whether that reading has
           * gone stale — so it is read from there rather than copied into a
           * second column that would then have to be kept true.
           */
          const observed = await repositories.processStates.find(server.id);
          return {
            id: server.id,
            slug: server.slug,
            displayName: server.displayName,
            environment: server.environment,
            desiredState: server.desiredState,
            observed:
              observed === undefined
                ? // Nobody has observed it, which is not the same as offline.
                  { lifecycle: 'unknown', observedAt: null, stale: null, pid: null }
                : {
                    lifecycle: observed.lifecycle,
                    observedAt: observed.observedAt,
                    stale: observed.stale,
                    pid: observed.observedPid ?? null,
                  },
            minecraftVersion: server.minecraftVersion,
            loader: server.loader,
            loaderVersion: server.loaderVersion,
            maxPlayers: server.maxPlayers,
            version: server.version,
            /** Whether it has been pointed at one, never at which one. */
            hasRunDirectory: server.runDirectory !== null,
            runtime: server.runtime,
            runtimeDetectedAt: server.runtimeDetectedAt,
          };
        }),
      ),
    }),
  );

  app.post<{ Body: CreateServerBody }>(
    '/api/v1/servers',
    {
      schema: { body: CreateServerBodySchema },
      preHandler: [authenticate, requirePermission('security.manage'), requireCsrf],
    },
    async (request, reply) => {
      // `ServerRepository.create` has existed since Phase 1 and nothing outside
      // a test ever called it, so the only way to register an instance was to
      // write SQL by hand — and every screen that needs a serverId was dead
      // until somebody did. Gated on `security.manage`, because an instance is
      // what every later permission ends up scoped to.
      const server = await repositories.servers.create({
        id: randomUUID(),
        slug: request.body.slug,
        displayName: request.body.displayName,
        environment: request.body.environment,
        minecraftVersion: request.body.minecraftVersion,
        loader: request.body.loader,
        loaderVersion: request.body.loaderVersion,
        maxPlayers: request.body.maxPlayers,
      });
      await repositories.audit.append(
        auditEvent({
          request,
          now: clock(),
          actor: { type: 'panel-user', id: request.authContext?.user.id ?? 'unknown' },
          action: 'server.create',
          resource: { type: 'server-instance', id: server.id },
          outcome: 'succeeded',
        }),
      );
      return reply.code(201).send(server);
    },
  );

  app.post<{ Params: { serverId: string }; Body: SetServerRuntimeBody }>(
    '/api/v1/servers/:serverId/runtime',
    {
      schema: { body: SetServerRuntimeSchema },
      preHandler: [authenticate, requirePermission('security.manage'), requireCsrf],
    },
    async (request) => {
      if (options.serverRuntimeDetector === undefined) {
        throw new ApiError(
          503,
          'RUNTIME_DETECTION_UNAVAILABLE',
          'A detecção de runtime não está configurada nesta instância.',
        );
      }
      const server = await repositories.servers.findById(request.params.serverId);
      if (server === undefined) {
        throw new ApiError(404, 'SERVER_NOT_FOUND', 'Instância não encontrada.');
      }

      let rootPath: string;
      let workspaceId: string | undefined;
      if ('workspaceId' in request.body) {
        const workspace = await repositories.workspaces.findById(request.body.workspaceId);
        if (workspace === undefined) {
          throw new ApiError(404, 'WORKSPACE_NOT_FOUND', 'Workspace não encontrado.');
        }
        if (workspace.kind !== 'server') {
          throw new ApiError(
            409,
            'WORKSPACE_NOT_SERVER',
            'Somente um workspace de servidor pode ser vinculado a uma instância.',
          );
        }
        rootPath = workspace.rootPath;
        workspaceId = workspace.workspaceId;
      } else {
        rootPath = request.body.rootPath;
      }

      // The runtime is read from the directory, never taken from the request.
      // A caller that could state the loader could state it wrong, and the
      // wrong launch plan runs a JVM where the world lives.
      const detected = await options.serverRuntimeDetector(rootPath);
      if ('refusal' in detected) {
        throw new ApiError(422, 'RUNTIME_NOT_RECOGNISED', detected.refusal);
      }

      try {
        await repositories.servers.setRuntime({
          id: server.id,
          runDirectory: detected.rootPath,
          runtime: detected.runtime,
          detectedAt: clock(),
          ...(workspaceId === undefined ? {} : { workspaceId }),
        });
      } catch (error) {
        if (!(error instanceof ServerRuntimeBindingError)) throw error;
        if (error.code === 'run-directory-taken') {
          throw new ApiError(
            409,
            'SERVER_RUNTIME_ALREADY_ASSIGNED',
            'Este diretório já pertence a outra instância.',
          );
        }
        if (error.code === 'server-already-linked') {
          throw new ApiError(
            409,
            'SERVER_INSTANCE_ALREADY_LINKED',
            'Esta instância já está vinculada a outro workspace.',
          );
        }
        if (error.code === 'process-owned') {
          throw new ApiError(
            409,
            'SERVER_PROCESS_OWNERSHIP_ACTIVE',
            'O runtime não pode ser alterado enquanto houver ownership de processo ativo ou incerto.',
          );
        }
        if (error.code === 'workspace-not-found') {
          throw new ApiError(404, 'WORKSPACE_NOT_FOUND', 'Workspace não encontrado.');
        }
        if (error.code === 'workspace-not-server') {
          throw new ApiError(409, 'WORKSPACE_NOT_SERVER', 'O workspace não representa um servidor.');
        }
        throw new ApiError(404, 'SERVER_NOT_FOUND', 'Instância não encontrada.');
      }
      await repositories.audit.append(
        auditEvent({
          request,
          now: clock(),
          actor: { type: 'panel-user', id: request.authContext?.user.id ?? 'unknown' },
          action: 'server.runtime.detected',
          resource: { type: 'server-instance', id: server.id },
          outcome: 'succeeded',
        }),
      );
      // The descriptor only, never the directory it was read from.
      return { runtime: detected.runtime };
    },
  );

  app.get(
    '/api/v1/audit',
    { preHandler: [authenticate, requirePermission('audit.view')] },
    async () => ({ events: await repositories.audit.list(100) }),
  );

  app.post<{ Body: AgentRegistrationBody }>(
    '/agent/v1/register/complete',
    {
      schema: { body: AgentRegistrationBodySchema },
      config: { rateLimit: { max: 5, timeWindow: '1 minute' } },
    },
    async (request, reply) => {
      const now = clock();
      const agent = await repositories.agents.register({
        agentId: request.body.agentId,
        serverInstanceId: request.body.serverInstanceId,
        tokenHash: hashOpaqueToken(request.body.provisioningToken),
        publicKeyPem: request.body.publicKeyPem,
        certificateFingerprint: request.body.certificateFingerprint,
        softwareVersion: request.body.softwareVersion,
        capabilities: request.body.capabilities,
        now,
      });
      if (agent === undefined) {
        throw new ApiError(401, 'PROVISIONING_TOKEN_INVALID', 'Provisionamento inválido ou expirado.');
      }
      await repositories.audit.append(
        auditEvent({
          request,
          now,
          actor: { type: 'agent', id: agent.id },
          action: 'agent.registered',
          resource: { type: 'server-instance', id: agent.serverInstanceId },
          outcome: 'succeeded',
        }),
      );
      return reply.code(201).send({ agentId: agent.id, status: agent.status });
    },
  );

  app.post<{ Body: AgentEnvelope }>(
    '/agent/v1/heartbeat',
    { schema: { body: AgentEnvelopeSchema } },
    async (request) => {
      const now = clock();
      const structural = validateAgentEnvelope(request.body);
      if (!structural.success || request.body.kind !== 'heartbeat') {
        throw new ApiError(400, 'AGENT_ENVELOPE_INVALID', 'Envelope do agente inválido.');
      }
      const agent = await repositories.agents.findById(request.body.agentId);
      if (agent === undefined || agent.serverInstanceId !== request.body.serverInstanceId) {
        throw new ApiError(401, 'AGENT_IDENTITY_INVALID', 'Identidade do agente inválida.');
      }
      if (!(await verifyAgentTransport(request, agent.certificateFingerprint))) {
        throw new ApiError(401, 'AGENT_TRANSPORT_INVALID', 'Transporte autenticado do agente inválido.');
      }
      if (
        !safeEqualHex(computeAgentPayloadHash(request.body), request.body.payloadHash) ||
        !verifyAgentEnvelopeSignature(request.body, createPublicKey(agent.publicKeyPem)) ||
        !isAgentEnvelopeFresh(request.body, { now })
      ) {
        throw new ApiError(401, 'AGENT_SIGNATURE_INVALID', 'Assinatura ou validade do agente inválida.');
      }
      const heartbeat = validateAgentHeartbeatPayload(request.body.payload.data);
      if (!heartbeat.success) {
        throw new ApiError(400, 'HEARTBEAT_PAYLOAD_INVALID', 'Payload de heartbeat inválido.');
      }
      const nonceAccepted = await repositories.agents.consumeNonce(
        agent.id,
        hashOpaqueToken(request.body.nonce),
        new Date(request.body.expiresAt),
        now,
      );
      if (!nonceAccepted) throw new ApiError(409, 'AGENT_REPLAY_DETECTED', 'Replay detectado.');
      await repositories.agents.recordHeartbeat({
        agentId: agent.id,
        status: heartbeat.value.status,
        softwareVersion: heartbeat.value.softwareVersion,
        protocolVersion: heartbeat.value.protocolVersion,
        capabilities: heartbeat.value.capabilities,
        observedAt: new Date(heartbeat.value.observedAt),
      });
      return { acceptedAt: now.toISOString(), nextHeartbeatSeconds: 30 };
    },
  );

  registerConfigurationRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: ConfigurationPermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'configuration-resource', id: input.resourceId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
    ...(options.configurationReader === undefined
      ? {}
      : { configurationReader: options.configurationReader }),
  });

  registerDatapackLoadOrderRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: DatapackLoadOrderPermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'ecosystem-analysis', id: input.analysisId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
  });

  registerAgentWorkRoutes(app, {
    repositories,
    clock,
    verifyAgentTransport,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    computePayloadHash: computeAgentPayloadHash,
    verifySignature: verifyAgentEnvelopeSignature,
    isFresh: isAgentEnvelopeFresh,
    safeEqualHex,
    hashNonce: hashOpaqueToken,
    newId: () => randomUUID(),
    audit: async (input) => {
      await repositories.audit.append({
        schemaVersion: 1,
        id: randomUUID(),
        occurredAt: clock().toISOString(),
        correlationId: input.correlationId,
        actor: { type: 'agent', id: input.agentId },
        source: 'agent',
        action: input.action,
        resource: { type: 'agent', id: input.agentId },
        outcome: input.outcome,
        ...(input.reason === undefined ? {} : { reason: input.reason }),
      });
    },
  });

  registerProcessRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: ProcessPermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    newId: () => randomUUID(),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'server-instance', id: input.serverId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
  });

  registerOperationalRoutes(app, {
    repositories,
    authenticate,
    requirePermission: (permission: OperationalPermission) => requirePermission(permission),
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
  });

  registerScheduleRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: SchedulePermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    newId: () => randomUUID(),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'server-instance', id: input.serverId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
  });

  registerTelemetryRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: TelemetryPermission) => requirePermission(permission),
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    ...(options.gameProviderConnected === undefined
      ? {}
      : { gameProviderConnected: options.gameProviderConnected }),
  });

  registerBackupRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: BackupPermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    newId: () => randomUUID(),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'server-instance', id: input.serverId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
  });

  registerAuthorizedFileRoutes(app, {
    clock,
    authenticate,
    requirePermission: (permission: AuthorizedFilePermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'authorized-file', id: input.rootId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
    ...(options.authorizedFiles === undefined
      ? {}
      : { authorizedFiles: options.authorizedFiles }),
  });

  registerArtifactRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: ArtifactPermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'artifact-submission', id: input.submissionId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
    ...(options.artifactQuarantineStore === undefined
      ? {}
      : { quarantineStore: options.artifactQuarantineStore }),
  });

  registerWorkspaceRoutes(app, {
    repositories,
    clock,
    authenticate,
    requirePermission: (permission: WorkspacePermission) => requirePermission(permission),
    requireCsrf,
    apiError: (statusCode, code, message) => new ApiError(statusCode, code, message),
    audit: async (input) => {
      await repositories.audit.append(
        auditEvent({
          request: input.request,
          now: clock(),
          actor: input.actor,
          action: input.action,
          resource: { type: 'workspace', id: input.workspaceId },
          outcome: input.outcome,
          ...(input.reason === undefined ? {} : { reason: input.reason }),
        }),
      );
    },
    ...(options.workspaceScanner === undefined
      ? {}
      : { scanner: options.workspaceScanner }),
    ...(options.workspaceEcosystem === undefined
      ? {}
      : { ecosystem: options.workspaceEcosystem }),
    ...(options.workspaceRootPolicy === undefined
      ? {}
      : { rootPolicy: options.workspaceRootPolicy }),
    ...(options.workspaceConfiguration === undefined
      ? {}
      : { configuration: options.workspaceConfiguration }),
    ...(options.sandboxLauncher === undefined ? {} : { sandbox: options.sandboxLauncher }),
    ...(options.releaseBuilder === undefined ? {} : { release: options.releaseBuilder }),
  });

  if (options.localOperator !== undefined) {
    registerLocalSession(app, {
      database: options.database,
      ownerEmail: options.localOperator.email,
      mode: options.localOperator.mode,
      ...(options.localOperator.mode === 'desktop'
        ? { launchToken: options.localOperator.launchToken }
        : {}),
      ...(options.panelEntryPath === undefined ? {} : { landing: options.panelEntryPath }),
      clock,
    });
  }

  // Last, so it can only ever answer what no route claimed.
  if (options.panelExportRoot !== undefined) {
    registerStaticPanel(app, {
      root: options.panelExportRoot,
      ...(options.localOperator?.mode !== 'development'
        ? {}
        : // With a local operator, the root is a sign-in that needs no typing.
          { entryPath: '/local/session' }),
    });
  }

  return app;
}

export type { ConfigurationValueReader } from './configuration-routes.js';
export type { ArtifactQuarantineStore } from './artifact-routes.js';

export function repositoriesFor(database: Database): Repositories {
  return createRepositories(database);
}
