%% Mapa geral de dependências confirmadas
graph TD
    n_aaa_particles_world["aaa_particles_world"]
    n_aaa_particles["aaa_particles"]
    n_aaa_particles_world -->|depende| n_aaa_particles
    n_aaa_particles_world["aaa_particles_world"]
    n_architectury["architectury"]
    n_aaa_particles_world -->|depende| n_architectury
    n_aether["aether"]
    n_curios["curios"]
    n_aether -->|depende| n_curios
    n_alexsmobs["alexsmobs"]
    n_citadel["citadel"]
    n_alexsmobs -->|depende| n_citadel
    n_ancient_obelisks["ancient_obelisks"]
    n_library_of_exile["library_of_exile"]
    n_ancient_obelisks -->|depende| n_library_of_exile
    n_antibonemeal["antibonemeal"]
    n_flib["flib"]
    n_antibonemeal -->|depende| n_flib
    n_apoli["apoli"]
    n_caelus["caelus"]
    n_apoli -->|depende| n_caelus
    n_apoli["apoli"]
    n_calio["calio"]
    n_apoli -->|depende| n_calio
    n_aquamirae["aquamirae"]
    n_obscure_api["obscure_api"]
    n_aquamirae -->|depende| n_obscure_api
    n_armoroftheages["armoroftheages"]
    n_yet_another_config_lib_v3["yet_another_config_lib_v3"]
    n_armoroftheages -->|depende| n_yet_another_config_lib_v3
    n_artifacts["artifacts"]
    n_architectury["architectury"]
    n_artifacts -->|depende| n_architectury
    n_artifacts["artifacts"]
    n_cloth_config["cloth_config"]
    n_artifacts -->|depende| n_cloth_config
    n_artifacts["artifacts"]
    n_curios["curios"]
    n_artifacts -->|depende| n_curios
    n_artifacts["artifacts"]
    n_expandability["expandability"]
    n_artifacts -->|depende| n_expandability
    n_attributeslib["attributeslib"]
    n_placebo["placebo"]
    n_attributeslib -->|depende| n_placebo
    n_betterendisland["betterendisland"]
    n_yungsapi["yungsapi"]
    n_betterendisland -->|depende| n_yungsapi
    n_betterlockon["betterlockon"]
    n_epicfight["epicfight"]
    n_betterlockon -->|depende| n_epicfight
    n_biomesoplenty["biomesoplenty"]
    n_terrablender["terrablender"]
    n_biomesoplenty -->|depende| n_terrablender
    n_biomeswevegone["biomeswevegone"]
    n_corgilib["corgilib"]
    n_biomeswevegone -->|depende| n_corgilib
    n_biomeswevegone["biomeswevegone"]
    n_geckolib["geckolib"]
    n_biomeswevegone -->|depende| n_geckolib
    n_biomeswevegone["biomeswevegone"]
    n_ohthetreesyoullgrow["ohthetreesyoullgrow"]
    n_biomeswevegone -->|depende| n_ohthetreesyoullgrow
    n_biomeswevegone["biomeswevegone"]
    n_terrablender["terrablender"]
    n_biomeswevegone -->|depende| n_terrablender
    n_blue_skies["blue_skies"]
    n_structure_gel["structure_gel"]
    n_blue_skies -->|depende| n_structure_gel
    n_bookofdragons["bookofdragons"]
    n_geckolib["geckolib"]
    n_bookofdragons -->|depende| n_geckolib
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cerbons_api["cerbons_api"]
    n_bosses_of_mass_destruction -->|depende| n_cerbons_api
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cloth_config["cloth_config"]
    n_bosses_of_mass_destruction -->|depende| n_cloth_config
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_geckolib["geckolib"]
    n_bosses_of_mass_destruction -->|depende| n_geckolib
    n_bountiful["bountiful"]
    n_kambrik["kambrik"]
    n_bountiful -->|depende| n_kambrik
    n_bountiful_npc["bountiful_npc"]
    n_bountiful["bountiful"]
    n_bountiful_npc -->|depende| n_bountiful
    n_cataclysm["cataclysm"]
    n_lionfishapi["lionfishapi"]
    n_cataclysm -->|depende| n_lionfishapi
    n_cataclysm_dimension["cataclysm_dimension"]
    n_cataclysm["cataclysm"]
    n_cataclysm_dimension -->|depende| n_cataclysm
    n_chatplus["chatplus"]
    n_architectury["architectury"]
    n_chatplus -->|depende| n_architectury
    n_chatplus["chatplus"]
    n_kotlinforforge["kotlinforforge"]
    n_chatplus -->|depende| n_kotlinforforge
    n_chipped["chipped"]
    n_athena["athena"]
    n_chipped -->|depende| n_athena
    n_chipped["chipped"]
    n_resourcefullib["resourcefullib"]
    n_chipped -->|depende| n_resourcefullib
    n_chloride["chloride"]
    n_embeddium["embeddium"]
    n_chloride -->|depende| n_embeddium
    n_chunksending["chunksending"]
    n_cupboard["cupboard"]
    n_chunksending -->|depende| n_cupboard
    n_cinematiccataclysm["cinematiccataclysm"]
    n_fdlib["fdlib"]
    n_cinematiccataclysm -->|depende| n_fdlib
    n_clearwater["clearwater"]
    n_resourcefulconfig["resourcefulconfig"]
    n_clearwater -->|depende| n_resourcefulconfig
    n_combatroll["combatroll"]
    n_cloth_config["cloth_config"]
    n_combatroll -->|depende| n_cloth_config
    n_combatroll["combatroll"]
    n_playeranimator["playeranimator"]
    n_combatroll -->|depende| n_playeranimator
    n_defaultoptions["defaultoptions"]
    n_balm["balm"]
    n_defaultoptions -->|depende| n_balm
    n_dodge_parry_reward["dodge_parry_reward"]
    n_epicfight["epicfight"]
    n_dodge_parry_reward -->|depende| n_epicfight
    n_dodosmobs["dodosmobs"]
    n_lionfishapi["lionfishapi"]
    n_dodosmobs -->|depende| n_lionfishapi
    n_domesticationinnovation["domesticationinnovation"]
    n_citadel["citadel"]
    n_domesticationinnovation -->|depende| n_citadel
    n_drippyloadingscreen["drippyloadingscreen"]
    n_fancymenu["fancymenu"]
    n_drippyloadingscreen -->|depende| n_fancymenu
    n_drippyloadingscreen["drippyloadingscreen"]
    n_konkrete["konkrete"]
    n_drippyloadingscreen -->|depende| n_konkrete
    n_dummmmmmy["dummmmmmy"]
    n_moonlight["moonlight"]
    n_dummmmmmy -->|depende| n_moonlight
    n_dungeon_realm["dungeon_realm"]
    n_library_of_exile["library_of_exile"]
    n_dungeon_realm -->|depende| n_library_of_exile
    n_efn["efn"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_efn -->|depende| n_epic_fight_avalon
    n_efn["efn"]
    n_epicfight["epicfight"]
    n_efn -->|depende| n_epicfight
    n_efn["efn"]
    n_invincible["invincible"]
    n_efn -->|depende| n_invincible
    n_efn_enhance["efn_enhance"]
    n_efn["efn"]
    n_efn_enhance -->|depende| n_efn
    n_efn_enhance["efn_enhance"]
    n_fancy_trail["fancy_trail"]
    n_efn_enhance -->|depende| n_fancy_trail
    n_enchantinginfuser["enchantinginfuser"]
    n_puzzleslib["puzzleslib"]
    n_enchantinginfuser -->|depende| n_puzzleslib
    n_enchdesc["enchdesc"]
    n_bookshelf["bookshelf"]
    n_enchdesc -->|depende| n_bookshelf
    n_entityjs["entityjs"]
    n_geckolib["geckolib"]
    n_entityjs -->|depende| n_geckolib
    n_entityjs["entityjs"]
    n_kubejs["kubejs"]
    n_entityjs -->|depende| n_kubejs
    n_epic_fight_avalon["epic_fight_avalon"]
    n_epicfight["epicfight"]
    n_epic_fight_avalon -->|depende| n_epicfight
    n_epicfightx["epicfightx"]
    n_epicfight["epicfight"]
    n_epicfightx -->|depende| n_epicfight
    n_falchionmoveset["falchionmoveset"]
    n_epicfight["epicfight"]
    n_falchionmoveset -->|depende| n_epicfight
    n_fallingtrees["fallingtrees"]
    n_architectury["architectury"]
    n_fallingtrees -->|depende| n_architectury
    n_fallingtrees["fallingtrees"]
    n_pandalib["pandalib"]
    n_fallingtrees -->|depende| n_pandalib
    n_fancymenu["fancymenu"]
    n_konkrete["konkrete"]
    n_fancymenu -->|depende| n_konkrete
    n_fancymenu["fancymenu"]
    n_melody["melody"]
    n_fancymenu -->|depende| n_melody
    n_fastasyncworldsave["fastasyncworldsave"]
    n_cupboard["cupboard"]
    n_fastasyncworldsave -->|depende| n_cupboard
    n_flerovium["flerovium"]
    n_embeddium["embeddium"]
    n_flerovium -->|depende| n_embeddium
    n_fruitsdelight["fruitsdelight"]
    n_farmersdelight["farmersdelight"]
    n_fruitsdelight -->|depende| n_farmersdelight
    n_fruitsdelight["fruitsdelight"]
    n_l2harvester["l2harvester"]
    n_fruitsdelight -->|depende| n_l2harvester
    n_ftbessentials["ftbessentials"]
    n_ftblibrary["ftblibrary"]
    n_ftbessentials -->|depende| n_ftblibrary
    n_ftblibrary["ftblibrary"]
    n_architectury["architectury"]
    n_ftblibrary -->|depende| n_architectury
    n_ftbquests["ftbquests"]
    n_architectury["architectury"]
    n_ftbquests -->|depende| n_architectury
    n_ftbquests["ftbquests"]
    n_ftblibrary["ftblibrary"]
    n_ftbquests -->|depende| n_ftblibrary
    n_ftbquests["ftbquests"]
    n_ftbteams["ftbteams"]
    n_ftbquests -->|depende| n_ftbteams
    n_ftbteams["ftbteams"]
    n_architectury["architectury"]
    n_ftbteams -->|depende| n_architectury
    n_ftbteams["ftbteams"]
    n_ftblibrary["ftblibrary"]
    n_ftbteams -->|depende| n_ftblibrary
    n_ftbxmodcompat["ftbxmodcompat"]
    n_architectury["architectury"]
    n_ftbxmodcompat -->|depende| n_architectury
    n_ftbxmodcompat["ftbxmodcompat"]
    n_ftblibrary["ftblibrary"]
    n_ftbxmodcompat -->|depende| n_ftblibrary
    n_graveyard["graveyard"]
    n_geckolib["geckolib"]
    n_graveyard -->|depende| n_geckolib
    n_indestructible["indestructible"]
    n_epicfight["epicfight"]
    n_indestructible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_irons_spellbooks["irons_spellbooks"]
    n_curios["curios"]
    n_irons_spellbooks -->|depende| n_curios
    n_irons_spellbooks["irons_spellbooks"]
    n_geckolib["geckolib"]
    n_irons_spellbooks -->|depende| n_geckolib
    n_irons_spellbooks["irons_spellbooks"]
    n_playeranimator["playeranimator"]
    n_irons_spellbooks -->|depende| n_playeranimator
    n_itemborders["itemborders"]
    n_iceberg["iceberg"]
    n_itemborders -->|depende| n_iceberg
    n_itemborders["itemborders"]
    n_prism["prism"]
    n_itemborders -->|depende| n_prism
    n_jadeaddons["jadeaddons"]
    n_jade["jade"]
    n_jadeaddons -->|depende| n_jade
    n_jeresources["jeresources"]
    n_jei["jei"]
    n_jeresources -->|depende| n_jei
    n_kubejs["kubejs"]
    n_architectury["architectury"]
    n_kubejs -->|depende| n_architectury
    n_kubejs["kubejs"]
    n_rhino["rhino"]
    n_kubejs -->|depende| n_rhino
    n_legendarytooltips["legendarytooltips"]
    n_iceberg["iceberg"]
    n_legendarytooltips -->|depende| n_iceberg
    n_legendarytooltips["legendarytooltips"]
    n_prism["prism"]
    n_legendarytooltips -->|depende| n_prism
    n_limitedchunks["limitedchunks"]
    n_cupboard["cupboard"]
    n_limitedchunks -->|depende| n_cupboard
    n_lost_aether_content["lost_aether_content"]
    n_aether["aether"]
    n_lost_aether_content -->|depende| n_aether
    n_lost_aether_content["lost_aether_content"]
    n_structure_gel["structure_gel"]
    n_lost_aether_content -->|depende| n_structure_gel
    n_magistuarmory["magistuarmory"]
    n_architectury["architectury"]
    n_magistuarmory -->|depende| n_architectury
    n_magistuarmory["magistuarmory"]
    n_cloth_config["cloth_config"]
    n_magistuarmory -->|depende| n_cloth_config
    n_mmorpg["mmorpg"]
    n_ancient_obelisks["ancient_obelisks"]
    n_mmorpg -->|depende| n_ancient_obelisks
    n_mmorpg["mmorpg"]
    n_curios["curios"]
    n_mmorpg -->|depende| n_curios
    n_mmorpg["mmorpg"]
    n_dungeon_realm["dungeon_realm"]
    n_mmorpg -->|depende| n_dungeon_realm
    n_mmorpg["mmorpg"]
    n_library_of_exile["library_of_exile"]
    n_mmorpg -->|depende| n_library_of_exile
    n_mmorpg["mmorpg"]
    n_playeranimator["playeranimator"]
    n_mmorpg -->|depende| n_playeranimator
    n_mmorpg["mmorpg"]
    n_the_harvest["the_harvest"]
    n_mmorpg -->|depende| n_the_harvest
    n_mns["mns"]
    n_moogs_structures["moogs_structures"]
    n_mns -->|depende| n_moogs_structures
    n_mns_compat["mns_compat"]
    n_mmorpg["mmorpg"]
    n_mns_compat -->|depende| n_mmorpg
    n_mowziesmobs["mowziesmobs"]
    n_geckolib["geckolib"]
    n_mowziesmobs -->|depende| n_geckolib
    n_noworldgenwarning["noworldgenwarning"]
    n_mixin_booster["mixin_booster"]
    n_noworldgenwarning -->|depende| n_mixin_booster
    n_origins["origins"]
    n_apoli["apoli"]
    n_origins -->|depende| n_apoli
    n_origins["origins"]
    n_calio["calio"]
    n_origins -->|depende| n_calio
    n_p1nero_bow["p1nero_bow"]
    n_epicfight["epicfight"]
    n_p1nero_bow -->|depende| n_epicfight
    n_p1nero_ec["p1nero_ec"]
    n_cataclysm["cataclysm"]
    n_p1nero_ec -->|depende| n_cataclysm
    n_p1nero_ec["p1nero_ec"]
    n_efn["efn"]
    n_p1nero_ec -->|depende| n_efn
    n_pandalib["pandalib"]
    n_architectury["architectury"]
    n_pandalib -->|depende| n_architectury
    n_ponder["ponder"]
    n_flywheel["flywheel"]
    n_ponder -->|depende| n_flywheel
    n_puzzleslib["puzzleslib"]
    n_puzzlesaccessapi["puzzlesaccessapi"]
    n_puzzleslib -->|depende| n_puzzlesaccessapi
    n_quark["quark"]
    n_zeta["zeta"]
    n_quark -->|depende| n_zeta
    n_radiantgear["radiantgear"]
    n_curios["curios"]
    n_radiantgear -->|depende| n_curios
    n_rebind_narrator["rebind_narrator"]
    n_modder_name_lib["modder_name_lib"]
    n_rebind_narrator -->|depende| n_modder_name_lib
    n_ribbits["ribbits"]
    n_geckolib["geckolib"]
    n_ribbits -->|depende| n_geckolib
    n_ribbits["ribbits"]
    n_yungsapi["yungsapi"]
    n_ribbits -->|depende| n_yungsapi
    n_rpg_origins["rpg_origins"]
    n_origins["origins"]
    n_rpg_origins -->|depende| n_origins
    n_saintsdragons["saintsdragons"]
    n_geckolib["geckolib"]
    n_saintsdragons -->|depende| n_geckolib
    n_simplyswords["simplyswords"]
    n_architectury["architectury"]
    n_simplyswords -->|depende| n_architectury
    n_simplyswords["simplyswords"]
    n_cloth_config["cloth_config"]
    n_simplyswords -->|depende| n_cloth_config
    n_smoothchunk["smoothchunk"]
    n_cupboard["cupboard"]
    n_smoothchunk -->|depende| n_cupboard
    n_soulslikeuniverse["soulslikeuniverse"]
    n_epicfight["epicfight"]
    n_soulslikeuniverse -->|depende| n_epicfight
    n_soulslikeuniverse["soulslikeuniverse"]
    n_wom["wom"]
    n_soulslikeuniverse -->|depende| n_wom
    n_structure_layout_optimizer["structure_layout_optimizer"]
    n_resourcefulconfig["resourcefulconfig"]
    n_structure_layout_optimizer -->|depende| n_resourcefulconfig
    n_super_golem["super_golem"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_golem -->|depende| n_epic_fight_avalon
    n_super_golem["super_golem"]
    n_epicfight["epicfight"]
    n_super_golem -->|depende| n_epicfight
    n_super_warden["super_warden"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_warden -->|depende| n_epic_fight_avalon
    n_super_warden["super_warden"]
    n_epicfight["epicfight"]
    n_super_warden -->|depende| n_epicfight
    n_supplementaries["supplementaries"]
    n_moonlight["moonlight"]
    n_supplementaries -->|depende| n_moonlight
    n_swem["swem"]
    n_geckolib["geckolib"]
    n_swem -->|depende| n_geckolib
    n_swem["swem"]
    n_playeranimator["playeranimator"]
    n_swem -->|depende| n_playeranimator
    n_sword_soaring["sword_soaring"]
    n_epicfight["epicfight"]
    n_sword_soaring -->|depende| n_epicfight
    n_sword_soaring["sword_soaring"]
    n_invincible["invincible"]
    n_sword_soaring -->|depende| n_invincible
    n_t_and_t["t_and_t"]
    n_cristellib["cristellib"]
    n_t_and_t -->|depende| n_cristellib
    n_taxfreelevels["taxfreelevels"]
    n_cloth_config["cloth_config"]
    n_taxfreelevels -->|depende| n_cloth_config
    n_tcr_bosses["tcr_bosses"]
    n_ba_bt["ba_bt"]
    n_tcr_bosses -->|depende| n_ba_bt
    n_tcr_bosses["tcr_bosses"]
    n_efn["efn"]
    n_tcr_bosses -->|depende| n_efn
    n_tcr_bosses["tcr_bosses"]
    n_epicfight["epicfight"]
    n_tcr_bosses -->|depende| n_epicfight
    n_tcrcore["tcrcore"]
    n_ba_bt["ba_bt"]
    n_tcrcore -->|depende| n_ba_bt
    n_tcrcore["tcrcore"]
    n_bookofdragons["bookofdragons"]
    n_tcrcore -->|depende| n_bookofdragons
    n_tcrcore["tcrcore"]
    n_cataclysm["cataclysm"]
    n_tcrcore -->|depende| n_cataclysm
    n_tcrcore["tcrcore"]
    n_combat_evolution["combat_evolution"]
    n_tcrcore -->|depende| n_combat_evolution
    n_tcrcore["tcrcore"]
    n_dodge_parry_reward["dodge_parry_reward"]
    n_tcrcore -->|depende| n_dodge_parry_reward
    n_tcrcore["tcrcore"]
    n_efn["efn"]
    n_tcrcore -->|depende| n_efn
    n_tcrcore["tcrcore"]
    n_epicfight["epicfight"]
    n_tcrcore -->|depende| n_epicfight
    n_tcrcore["tcrcore"]
    n_epicskills["epicskills"]
    n_tcrcore -->|depende| n_epicskills
    n_tcrcore["tcrcore"]
    n_indestructible["indestructible"]
    n_tcrcore -->|depende| n_indestructible
    n_tcrcore["tcrcore"]
    n_irons_spellbooks["irons_spellbooks"]
    n_tcrcore -->|depende| n_irons_spellbooks
    n_tcrcore["tcrcore"]
    n_p1nero_ec["p1nero_ec"]
    n_tcrcore -->|depende| n_p1nero_ec
    n_tcrcore["tcrcore"]
    n_super_golem["super_golem"]
    n_tcrcore -->|depende| n_super_golem
    n_tcrcore["tcrcore"]
    n_sword_soaring["sword_soaring"]
    n_tcrcore -->|depende| n_sword_soaring
    n_the_harvest["the_harvest"]
    n_library_of_exile["library_of_exile"]
    n_the_harvest -->|depende| n_library_of_exile
    n_travelerstitles["travelerstitles"]
    n_yungsapi["yungsapi"]
    n_travelerstitles -->|depende| n_yungsapi
    n_tudigong["tudigong"]
    n_p1nero_dl["p1nero_dl"]
    n_tudigong -->|depende| n_p1nero_dl
    n_uniqueaccessories["uniqueaccessories"]
    n_attributeslib["attributeslib"]
    n_uniqueaccessories -->|depende| n_attributeslib
    n_uniqueaccessories["uniqueaccessories"]
    n_cloth_config["cloth_config"]
    n_uniqueaccessories -->|depende| n_cloth_config
