%% Tecnologia, magia, mundo e progressão
graph TD
    n_aether["aether"]
    n_curios["curios"]
    n_aether -->|depende| n_curios
    n_alexsmobs["alexsmobs"]
    n_citadel["citadel"]
    n_alexsmobs -->|depende| n_citadel
    n_ancient_obelisks["ancient_obelisks"]
    n_library_of_exile["library_of_exile"]
    n_ancient_obelisks -->|depende| n_library_of_exile
    n_armoroftheages["armoroftheages"]
    n_yet_another_config_lib_v3["yet_another_config_lib_v3"]
    n_armoroftheages -->|depende| n_yet_another_config_lib_v3
    n_betterendisland["betterendisland"]
    n_yungsapi["yungsapi"]
    n_betterendisland -->|depende| n_yungsapi
    n_betterlockon["betterlockon"]
    n_epicfight["epicfight"]
    n_betterlockon -->|depende| n_epicfight
    n_biomesoplenty["biomesoplenty"]
    n_terrablender["terrablender"]
    n_biomesoplenty -->|depende| n_terrablender
    n_biomeswevegone["biomeswevegone"]
    n_corgilib["corgilib"]
    n_biomeswevegone -->|depende| n_corgilib
    n_biomeswevegone["biomeswevegone"]
    n_geckolib["geckolib"]
    n_biomeswevegone -->|depende| n_geckolib
    n_biomeswevegone["biomeswevegone"]
    n_ohthetreesyoullgrow["ohthetreesyoullgrow"]
    n_biomeswevegone -->|depende| n_ohthetreesyoullgrow
    n_biomeswevegone["biomeswevegone"]
    n_terrablender["terrablender"]
    n_biomeswevegone -->|depende| n_terrablender
    n_blue_skies["blue_skies"]
    n_structure_gel["structure_gel"]
    n_blue_skies -->|depende| n_structure_gel
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cerbons_api["cerbons_api"]
    n_bosses_of_mass_destruction -->|depende| n_cerbons_api
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cloth_config["cloth_config"]
    n_bosses_of_mass_destruction -->|depende| n_cloth_config
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_geckolib["geckolib"]
    n_bosses_of_mass_destruction -->|depende| n_geckolib
    n_bountiful["bountiful"]
    n_kambrik["kambrik"]
    n_bountiful -->|depende| n_kambrik
    n_bountiful_npc["bountiful_npc"]
    n_bountiful["bountiful"]
    n_bountiful_npc -->|depende| n_bountiful
    n_cataclysm_dimension["cataclysm_dimension"]
    n_cataclysm["cataclysm"]
    n_cataclysm_dimension -->|depende| n_cataclysm
    n_cinematiccataclysm["cinematiccataclysm"]
    n_fdlib["fdlib"]
    n_cinematiccataclysm -->|depende| n_fdlib
    n_combatroll["combatroll"]
    n_cloth_config["cloth_config"]
    n_combatroll -->|depende| n_cloth_config
    n_combatroll["combatroll"]
    n_playeranimator["playeranimator"]
    n_combatroll -->|depende| n_playeranimator
    n_dodge_parry_reward["dodge_parry_reward"]
    n_epicfight["epicfight"]
    n_dodge_parry_reward -->|depende| n_epicfight
    n_dodosmobs["dodosmobs"]
    n_lionfishapi["lionfishapi"]
    n_dodosmobs -->|depende| n_lionfishapi
    n_domesticationinnovation["domesticationinnovation"]
    n_citadel["citadel"]
    n_domesticationinnovation -->|depende| n_citadel
    n_dungeon_realm["dungeon_realm"]
    n_library_of_exile["library_of_exile"]
    n_dungeon_realm -->|depende| n_library_of_exile
    n_efn["efn"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_efn -->|depende| n_epic_fight_avalon
    n_efn["efn"]
    n_epicfight["epicfight"]
    n_efn -->|depende| n_epicfight
    n_efn["efn"]
    n_invincible["invincible"]
    n_efn -->|depende| n_invincible
    n_efn_enhance["efn_enhance"]
    n_efn["efn"]
    n_efn_enhance -->|depende| n_efn
    n_enchantinginfuser["enchantinginfuser"]
    n_puzzleslib["puzzleslib"]
    n_enchantinginfuser -->|depende| n_puzzleslib
    n_epic_fight_avalon["epic_fight_avalon"]
    n_epicfight["epicfight"]
    n_epic_fight_avalon -->|depende| n_epicfight
    n_epicfightx["epicfightx"]
    n_epicfight["epicfight"]
    n_epicfightx -->|depende| n_epicfight
    n_falchionmoveset["falchionmoveset"]
    n_epicfight["epicfight"]
    n_falchionmoveset -->|depende| n_epicfight
    n_fruitsdelight["fruitsdelight"]
    n_l2harvester["l2harvester"]
    n_fruitsdelight -->|depende| n_l2harvester
    n_ftbquests["ftbquests"]
    n_architectury["architectury"]
    n_ftbquests -->|depende| n_architectury
    n_ftbquests["ftbquests"]
    n_ftblibrary["ftblibrary"]
    n_ftbquests -->|depende| n_ftblibrary
    n_ftbquests["ftbquests"]
    n_ftbteams["ftbteams"]
    n_ftbquests -->|depende| n_ftbteams
    n_graveyard["graveyard"]
    n_geckolib["geckolib"]
    n_graveyard -->|depende| n_geckolib
    n_indestructible["indestructible"]
    n_epicfight["epicfight"]
    n_indestructible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_irons_spellbooks["irons_spellbooks"]
    n_curios["curios"]
    n_irons_spellbooks -->|depende| n_curios
    n_irons_spellbooks["irons_spellbooks"]
    n_geckolib["geckolib"]
    n_irons_spellbooks -->|depende| n_geckolib
    n_irons_spellbooks["irons_spellbooks"]
    n_playeranimator["playeranimator"]
    n_irons_spellbooks -->|depende| n_playeranimator
    n_lost_aether_content["lost_aether_content"]
    n_aether["aether"]
    n_lost_aether_content -->|depende| n_aether
    n_lost_aether_content["lost_aether_content"]
    n_structure_gel["structure_gel"]
    n_lost_aether_content -->|depende| n_structure_gel
    n_magistuarmory["magistuarmory"]
    n_architectury["architectury"]
    n_magistuarmory -->|depende| n_architectury
    n_magistuarmory["magistuarmory"]
    n_cloth_config["cloth_config"]
    n_magistuarmory -->|depende| n_cloth_config
    n_mmorpg["mmorpg"]
    n_ancient_obelisks["ancient_obelisks"]
    n_mmorpg -->|depende| n_ancient_obelisks
    n_mmorpg["mmorpg"]
    n_curios["curios"]
    n_mmorpg -->|depende| n_curios
    n_mmorpg["mmorpg"]
    n_dungeon_realm["dungeon_realm"]
    n_mmorpg -->|depende| n_dungeon_realm
    n_mmorpg["mmorpg"]
    n_library_of_exile["library_of_exile"]
    n_mmorpg -->|depende| n_library_of_exile
    n_mmorpg["mmorpg"]
    n_playeranimator["playeranimator"]
    n_mmorpg -->|depende| n_playeranimator
    n_mmorpg["mmorpg"]
    n_the_harvest["the_harvest"]
    n_mmorpg -->|depende| n_the_harvest
    n_mns["mns"]
    n_moogs_structures["moogs_structures"]
    n_mns -->|depende| n_moogs_structures
    n_mns_compat["mns_compat"]
    n_mmorpg["mmorpg"]
    n_mns_compat -->|depende| n_mmorpg
    n_mowziesmobs["mowziesmobs"]
    n_geckolib["geckolib"]
    n_mowziesmobs -->|depende| n_geckolib
    n_noworldgenwarning["noworldgenwarning"]
    n_mixin_booster["mixin_booster"]
    n_noworldgenwarning -->|depende| n_mixin_booster
    n_p1nero_bow["p1nero_bow"]
    n_epicfight["epicfight"]
    n_p1nero_bow -->|depende| n_epicfight
    n_p1nero_ec["p1nero_ec"]
    n_cataclysm["cataclysm"]
    n_p1nero_ec -->|depende| n_cataclysm
    n_p1nero_ec["p1nero_ec"]
    n_efn["efn"]
    n_p1nero_ec -->|depende| n_efn
    n_puzzleslib["puzzleslib"]
    n_puzzlesaccessapi["puzzlesaccessapi"]
    n_puzzleslib -->|depende| n_puzzlesaccessapi
    n_rpg_origins["rpg_origins"]
    n_origins["origins"]
    n_rpg_origins -->|depende| n_origins
    n_simplyswords["simplyswords"]
    n_architectury["architectury"]
    n_simplyswords -->|depende| n_architectury
    n_simplyswords["simplyswords"]
    n_cloth_config["cloth_config"]
    n_simplyswords -->|depende| n_cloth_config
    n_soulslikeuniverse["soulslikeuniverse"]
    n_epicfight["epicfight"]
    n_soulslikeuniverse -->|depende| n_epicfight
    n_soulslikeuniverse["soulslikeuniverse"]
    n_wom["wom"]
    n_soulslikeuniverse -->|depende| n_wom
    n_structure_layout_optimizer["structure_layout_optimizer"]
    n_resourcefulconfig["resourcefulconfig"]
    n_structure_layout_optimizer -->|depende| n_resourcefulconfig
    n_super_golem["super_golem"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_golem -->|depende| n_epic_fight_avalon
    n_super_golem["super_golem"]
    n_epicfight["epicfight"]
    n_super_golem -->|depende| n_epicfight
    n_super_warden["super_warden"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_warden -->|depende| n_epic_fight_avalon
    n_super_warden["super_warden"]
    n_epicfight["epicfight"]
    n_super_warden -->|depende| n_epicfight
    n_swem["swem"]
    n_geckolib["geckolib"]
    n_swem -->|depende| n_geckolib
    n_swem["swem"]
    n_playeranimator["playeranimator"]
    n_swem -->|depende| n_playeranimator
    n_sword_soaring["sword_soaring"]
    n_epicfight["epicfight"]
    n_sword_soaring -->|depende| n_epicfight
    n_sword_soaring["sword_soaring"]
    n_invincible["invincible"]
    n_sword_soaring -->|depende| n_invincible
    n_t_and_t["t_and_t"]
    n_cristellib["cristellib"]
    n_t_and_t -->|depende| n_cristellib
    n_taxfreelevels["taxfreelevels"]
    n_cloth_config["cloth_config"]
    n_taxfreelevels -->|depende| n_cloth_config
    n_tcr_bosses["tcr_bosses"]
    n_ba_bt["ba_bt"]
    n_tcr_bosses -->|depende| n_ba_bt
    n_tcr_bosses["tcr_bosses"]
    n_efn["efn"]
    n_tcr_bosses -->|depende| n_efn
    n_tcr_bosses["tcr_bosses"]
    n_epicfight["epicfight"]
    n_tcr_bosses -->|depende| n_epicfight
    n_tcrcore["tcrcore"]
    n_ba_bt["ba_bt"]
    n_tcrcore -->|depende| n_ba_bt
    n_tcrcore["tcrcore"]
    n_combat_evolution["combat_evolution"]
    n_tcrcore -->|depende| n_combat_evolution
    n_tcrcore["tcrcore"]
    n_dodge_parry_reward["dodge_parry_reward"]
    n_tcrcore -->|depende| n_dodge_parry_reward
    n_tcrcore["tcrcore"]
    n_efn["efn"]
    n_tcrcore -->|depende| n_efn
    n_tcrcore["tcrcore"]
    n_epicfight["epicfight"]
    n_tcrcore -->|depende| n_epicfight
    n_tcrcore["tcrcore"]
    n_epicskills["epicskills"]
    n_tcrcore -->|depende| n_epicskills
    n_tcrcore["tcrcore"]
    n_irons_spellbooks["irons_spellbooks"]
    n_tcrcore -->|depende| n_irons_spellbooks
    n_tcrcore["tcrcore"]
    n_p1nero_ec["p1nero_ec"]
    n_tcrcore -->|depende| n_p1nero_ec
    n_tcrcore["tcrcore"]
    n_super_golem["super_golem"]
    n_tcrcore -->|depende| n_super_golem
    n_tcrcore["tcrcore"]
    n_sword_soaring["sword_soaring"]
    n_tcrcore -->|depende| n_sword_soaring
    n_the_harvest["the_harvest"]
    n_library_of_exile["library_of_exile"]
    n_the_harvest -->|depende| n_library_of_exile
    n_travelerstitles["travelerstitles"]
    n_yungsapi["yungsapi"]
    n_travelerstitles -->|depende| n_yungsapi
    n_uniqueaccessories["uniqueaccessories"]
    n_attributeslib["attributeslib"]
    n_uniqueaccessories -->|depende| n_attributeslib
    n_uniqueaccessories["uniqueaccessories"]
    n_cloth_config["cloth_config"]
    n_uniqueaccessories -->|depende| n_cloth_config
    n_uniqueaccessories["uniqueaccessories"]
    n_curios["curios"]
    n_uniqueaccessories -->|depende| n_curios
    n_void_mns_prof_compat["void_mns_prof_compat"]
    n_mmorpg["mmorpg"]
    n_void_mns_prof_compat -->|depende| n_mmorpg
    n_wom["wom"]
    n_epicfight["epicfight"]
    n_wom -->|depende| n_epicfight
    n_wom["wom"]
    n_epicfight["epicfight"]
    n_wom -->|depende| n_epicfight
    n_wraithon["wraithon"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_wraithon -->|depende| n_epic_fight_avalon
    n_wraithon["wraithon"]
    n_epicfight["epicfight"]
    n_wraithon -->|depende| n_epicfight
    n_configured["configured"]
    n_jei["jei"]
    n_configured -.->|opcional| n_jei
    n_easy_npc["easy_npc"]
    n_armourers_workshop["armourers_workshop"]
    n_easy_npc -.->|opcional| n_armourers_workshop
    n_epicfightx["epicfightx"]
    n_p1nero_bow["p1nero_bow"]
    n_epicfightx -.->|opcional| n_p1nero_bow
    n_ftblibrary["ftblibrary"]
    n_ftbquests["ftbquests"]
    n_ftblibrary -.->|opcional| n_ftbquests
    n_ftbxmodcompat["ftbxmodcompat"]
    n_ftbquests["ftbquests"]
    n_ftbxmodcompat -.->|opcional| n_ftbquests
    n_goblins_tyranny["goblins_tyranny"]
    n_geckolib["geckolib"]
    n_goblins_tyranny -.->|opcional| n_geckolib
    n_goblins_tyranny["goblins_tyranny"]
    n_jei["jei"]
    n_goblins_tyranny -.->|opcional| n_jei
    n_p1nero_bow["p1nero_bow"]
    n_epicfightx["epicfightx"]
    n_p1nero_bow -.->|opcional| n_epicfightx
    n_parcool["parcool"]
    n_epicfight["epicfight"]
    n_parcool -.->|opcional| n_epicfight
    n_roe_weapons["roe_weapons"]
    n_curios["curios"]
    n_roe_weapons -.->|opcional| n_curios
    n_summoningrituals["summoningrituals"]
    n_jei["jei"]
    n_summoningrituals -.->|opcional| n_jei
    n_summoningrituals["summoningrituals"]
    n_kubejs["kubejs"]
    n_summoningrituals -.->|opcional| n_kubejs
    n_combatroll["combatroll"]
    n_bettercombat["bettercombat"]
    n_combatroll -.->|opcional ausente| n_bettercombat
    n_configured["configured"]
    n_catalogue["catalogue"]
    n_configured -.->|opcional ausente| n_catalogue
    n_configured["configured"]
    n_framework["framework"]
    n_configured -.->|opcional ausente| n_framework
    n_epicfightx["epicfightx"]
    n_dualgreatswords["dualgreatswords"]
    n_epicfightx -.->|opcional ausente| n_dualgreatswords
    n_ftbquests["ftbquests"]
    n_itemfilters["itemfilters"]
    n_ftbquests -.->|opcional ausente| n_itemfilters
    n_lightmanscurrency["lightmanscurrency"]
    n_lightmansdiscord["lightmansdiscord"]
    n_lightmanscurrency -.->|opcional ausente| n_lightmansdiscord
    n_shinyhorses["shinyhorses"]
    n_simplekelpies["simplekelpies"]
    n_shinyhorses -.->|opcional ausente| n_simplekelpies
    n_summoningrituals["summoningrituals"]
    n_roughlyenoughitems["roughlyenoughitems"]
    n_summoningrituals -.->|opcional ausente| n_roughlyenoughitems
    n_swem["swem"]
    n_placeableitems["placeableitems"]
    n_swem -.->|opcional ausente| n_placeableitems
