%% Tecnologia, magia, mundo e progressão
graph TD
    n_aether["aether"]
    n_curios["curios"]
    n_aether -->|depende| n_curios
    n_aether["aether"]
    n_curios["curios"]
    n_aether -->|depende| n_curios
    n_alexsmobs["alexsmobs"]
    n_citadel["citadel"]
    n_alexsmobs -->|depende| n_citadel
    n_alexsmobs["alexsmobs"]
    n_citadel["citadel"]
    n_alexsmobs -->|depende| n_citadel
    n_ancient_obelisks["ancient_obelisks"]
    n_library_of_exile["library_of_exile"]
    n_ancient_obelisks -->|depende| n_library_of_exile
    n_ancient_obelisks["ancient_obelisks"]
    n_library_of_exile["library_of_exile"]
    n_ancient_obelisks -->|depende| n_library_of_exile
    n_ancient_obelisks["ancient_obelisks"]
    n_library_of_exile["library_of_exile"]
    n_ancient_obelisks -->|depende| n_library_of_exile
    n_armoroftheages["armoroftheages"]
    n_yet_another_config_lib_v3["yet_another_config_lib_v3"]
    n_armoroftheages -->|depende| n_yet_another_config_lib_v3
    n_betterendisland["betterendisland"]
    n_yungsapi["yungsapi"]
    n_betterendisland -->|depende| n_yungsapi
    n_betterendisland["betterendisland"]
    n_yungsapi["yungsapi"]
    n_betterendisland -->|depende| n_yungsapi
    n_betterlockon["betterlockon"]
    n_epicfight["epicfight"]
    n_betterlockon -->|depende| n_epicfight
    n_biomesoplenty["biomesoplenty"]
    n_terrablender["terrablender"]
    n_biomesoplenty -->|depende| n_terrablender
    n_biomeswevegone["biomeswevegone"]
    n_corgilib["corgilib"]
    n_biomeswevegone -->|depende| n_corgilib
    n_biomeswevegone["biomeswevegone"]
    n_corgilib["corgilib"]
    n_biomeswevegone -->|depende| n_corgilib
    n_biomeswevegone["biomeswevegone"]
    n_geckolib["geckolib"]
    n_biomeswevegone -->|depende| n_geckolib
    n_biomeswevegone["biomeswevegone"]
    n_geckolib["geckolib"]
    n_biomeswevegone -->|depende| n_geckolib
    n_biomeswevegone["biomeswevegone"]
    n_ohthetreesyoullgrow["ohthetreesyoullgrow"]
    n_biomeswevegone -->|depende| n_ohthetreesyoullgrow
    n_biomeswevegone["biomeswevegone"]
    n_ohthetreesyoullgrow["ohthetreesyoullgrow"]
    n_biomeswevegone -->|depende| n_ohthetreesyoullgrow
    n_biomeswevegone["biomeswevegone"]
    n_terrablender["terrablender"]
    n_biomeswevegone -->|depende| n_terrablender
    n_biomeswevegone["biomeswevegone"]
    n_terrablender["terrablender"]
    n_biomeswevegone -->|depende| n_terrablender
    n_blue_skies["blue_skies"]
    n_structure_gel["structure_gel"]
    n_blue_skies -->|depende| n_structure_gel
    n_blue_skies["blue_skies"]
    n_structure_gel["structure_gel"]
    n_blue_skies -->|depende| n_structure_gel
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cerbons_api["cerbons_api"]
    n_bosses_of_mass_destruction -->|depende| n_cerbons_api
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cerbons_api["cerbons_api"]
    n_bosses_of_mass_destruction -->|depende| n_cerbons_api
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cloth_config["cloth_config"]
    n_bosses_of_mass_destruction -->|depende| n_cloth_config
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_cloth_config["cloth_config"]
    n_bosses_of_mass_destruction -->|depende| n_cloth_config
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_geckolib["geckolib"]
    n_bosses_of_mass_destruction -->|depende| n_geckolib
    n_bosses_of_mass_destruction["bosses_of_mass_destruction"]
    n_geckolib["geckolib"]
    n_bosses_of_mass_destruction -->|depende| n_geckolib
    n_bountiful["bountiful"]
    n_kambrik["kambrik"]
    n_bountiful -->|depende| n_kambrik
    n_bountiful["bountiful"]
    n_kambrik["kambrik"]
    n_bountiful -->|depende| n_kambrik
    n_bountiful_npc["bountiful_npc"]
    n_bountiful["bountiful"]
    n_bountiful_npc -->|depende| n_bountiful
    n_bountiful_npc["bountiful_npc"]
    n_bountiful["bountiful"]
    n_bountiful_npc -->|depende| n_bountiful
    n_cataclysm_dimension["cataclysm_dimension"]
    n_cataclysm["cataclysm"]
    n_cataclysm_dimension -->|depende| n_cataclysm
    n_cataclysm_dimension["cataclysm_dimension"]
    n_cataclysm["cataclysm"]
    n_cataclysm_dimension -->|depende| n_cataclysm
    n_cinematiccataclysm["cinematiccataclysm"]
    n_fdlib["fdlib"]
    n_cinematiccataclysm -->|depende| n_fdlib
    n_cinematiccataclysm["cinematiccataclysm"]
    n_fdlib["fdlib"]
    n_cinematiccataclysm -->|depende| n_fdlib
    n_combatroll["combatroll"]
    n_cloth_config["cloth_config"]
    n_combatroll -->|depende| n_cloth_config
    n_combatroll["combatroll"]
    n_cloth_config["cloth_config"]
    n_combatroll -->|depende| n_cloth_config
    n_combatroll["combatroll"]
    n_playeranimator["playeranimator"]
    n_combatroll -->|depende| n_playeranimator
    n_combatroll["combatroll"]
    n_playeranimator["playeranimator"]
    n_combatroll -->|depende| n_playeranimator
    n_dodge_parry_reward["dodge_parry_reward"]
    n_epicfight["epicfight"]
    n_dodge_parry_reward -->|depende| n_epicfight
    n_dodge_parry_reward["dodge_parry_reward"]
    n_epicfight["epicfight"]
    n_dodge_parry_reward -->|depende| n_epicfight
    n_dodosmobs["dodosmobs"]
    n_lionfishapi["lionfishapi"]
    n_dodosmobs -->|depende| n_lionfishapi
    n_dodosmobs["dodosmobs"]
    n_lionfishapi["lionfishapi"]
    n_dodosmobs -->|depende| n_lionfishapi
    n_domesticationinnovation["domesticationinnovation"]
    n_citadel["citadel"]
    n_domesticationinnovation -->|depende| n_citadel
    n_domesticationinnovation["domesticationinnovation"]
    n_citadel["citadel"]
    n_domesticationinnovation -->|depende| n_citadel
    n_dungeon_realm["dungeon_realm"]
    n_library_of_exile["library_of_exile"]
    n_dungeon_realm -->|depende| n_library_of_exile
    n_dungeon_realm["dungeon_realm"]
    n_library_of_exile["library_of_exile"]
    n_dungeon_realm -->|depende| n_library_of_exile
    n_dungeon_realm["dungeon_realm"]
    n_library_of_exile["library_of_exile"]
    n_dungeon_realm -->|depende| n_library_of_exile
    n_efn["efn"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_efn -->|depende| n_epic_fight_avalon
    n_efn["efn"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_efn -->|depende| n_epic_fight_avalon
    n_efn["efn"]
    n_epicfight["epicfight"]
    n_efn -->|depende| n_epicfight
    n_efn["efn"]
    n_epicfight["epicfight"]
    n_efn -->|depende| n_epicfight
    n_efn["efn"]
    n_invincible["invincible"]
    n_efn -->|depende| n_invincible
    n_efn["efn"]
    n_invincible["invincible"]
    n_efn -->|depende| n_invincible
    n_efn_enhance["efn_enhance"]
    n_efn["efn"]
    n_efn_enhance -->|depende| n_efn
    n_efn_enhance["efn_enhance"]
    n_efn["efn"]
    n_efn_enhance -->|depende| n_efn
    n_enchantinginfuser["enchantinginfuser"]
    n_puzzleslib["puzzleslib"]
    n_enchantinginfuser -->|depende| n_puzzleslib
    n_enchantinginfuser["enchantinginfuser"]
    n_puzzleslib["puzzleslib"]
    n_enchantinginfuser -->|depende| n_puzzleslib
    n_enchantinginfuser["enchantinginfuser"]
    n_puzzleslib["puzzleslib"]
    n_enchantinginfuser -->|depende| n_puzzleslib
    n_epic_fight_avalon["epic_fight_avalon"]
    n_epicfight["epicfight"]
    n_epic_fight_avalon -->|depende| n_epicfight
    n_epic_fight_avalon["epic_fight_avalon"]
    n_epicfight["epicfight"]
    n_epic_fight_avalon -->|depende| n_epicfight
    n_epicfightx["epicfightx"]
    n_epicfight["epicfight"]
    n_epicfightx -->|depende| n_epicfight
    n_epicfightx["epicfightx"]
    n_epicfight["epicfight"]
    n_epicfightx -->|depende| n_epicfight
    n_fruitsdelight["fruitsdelight"]
    n_l2harvester["l2harvester"]
    n_fruitsdelight -->|depende| n_l2harvester
    n_fruitsdelight["fruitsdelight"]
    n_l2harvester["l2harvester"]
    n_fruitsdelight -->|depende| n_l2harvester
    n_ftbquests["ftbquests"]
    n_architectury["architectury"]
    n_ftbquests -->|depende| n_architectury
    n_ftbquests["ftbquests"]
    n_architectury["architectury"]
    n_ftbquests -->|depende| n_architectury
    n_ftbquests["ftbquests"]
    n_ftblibrary["ftblibrary"]
    n_ftbquests -->|depende| n_ftblibrary
    n_ftbquests["ftbquests"]
    n_ftblibrary["ftblibrary"]
    n_ftbquests -->|depende| n_ftblibrary
    n_ftbquests["ftbquests"]
    n_ftbteams["ftbteams"]
    n_ftbquests -->|depende| n_ftbteams
    n_ftbquests["ftbquests"]
    n_ftbteams["ftbteams"]
    n_ftbquests -->|depende| n_ftbteams
    n_indestructible["indestructible"]
    n_epicfight["epicfight"]
    n_indestructible -->|depende| n_epicfight
    n_indestructible["indestructible"]
    n_epicfight["epicfight"]
    n_indestructible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_invincible["invincible"]
    n_epicfight["epicfight"]
    n_invincible -->|depende| n_epicfight
    n_lost_aether_content["lost_aether_content"]
    n_aether["aether"]
    n_lost_aether_content -->|depende| n_aether
    n_lost_aether_content["lost_aether_content"]
    n_aether["aether"]
    n_lost_aether_content -->|depende| n_aether
    n_lost_aether_content["lost_aether_content"]
    n_structure_gel["structure_gel"]
    n_lost_aether_content -->|depende| n_structure_gel
    n_lost_aether_content["lost_aether_content"]
    n_structure_gel["structure_gel"]
    n_lost_aether_content -->|depende| n_structure_gel
    n_magistuarmory["magistuarmory"]
    n_architectury["architectury"]
    n_magistuarmory -->|depende| n_architectury
    n_magistuarmory["magistuarmory"]
    n_architectury["architectury"]
    n_magistuarmory -->|depende| n_architectury
    n_magistuarmory["magistuarmory"]
    n_cloth_config["cloth_config"]
    n_magistuarmory -->|depende| n_cloth_config
    n_magistuarmory["magistuarmory"]
    n_cloth_config["cloth_config"]
    n_magistuarmory -->|depende| n_cloth_config
    n_mmorpg["mmorpg"]
    n_ancient_obelisks["ancient_obelisks"]
    n_mmorpg -->|depende| n_ancient_obelisks
    n_mmorpg["mmorpg"]
    n_ancient_obelisks["ancient_obelisks"]
    n_mmorpg -->|depende| n_ancient_obelisks
    n_mmorpg["mmorpg"]
    n_ancient_obelisks["ancient_obelisks"]
    n_mmorpg -->|depende| n_ancient_obelisks
    n_mmorpg["mmorpg"]
    n_curios["curios"]
    n_mmorpg -->|depende| n_curios
    n_mmorpg["mmorpg"]
    n_curios["curios"]
    n_mmorpg -->|depende| n_curios
    n_mmorpg["mmorpg"]
    n_curios["curios"]
    n_mmorpg -->|depende| n_curios
    n_mmorpg["mmorpg"]
    n_dungeon_realm["dungeon_realm"]
    n_mmorpg -->|depende| n_dungeon_realm
    n_mmorpg["mmorpg"]
    n_dungeon_realm["dungeon_realm"]
    n_mmorpg -->|depende| n_dungeon_realm
    n_mmorpg["mmorpg"]
    n_dungeon_realm["dungeon_realm"]
    n_mmorpg -->|depende| n_dungeon_realm
    n_mmorpg["mmorpg"]
    n_library_of_exile["library_of_exile"]
    n_mmorpg -->|depende| n_library_of_exile
    n_mmorpg["mmorpg"]
    n_library_of_exile["library_of_exile"]
    n_mmorpg -->|depende| n_library_of_exile
    n_mmorpg["mmorpg"]
    n_library_of_exile["library_of_exile"]
    n_mmorpg -->|depende| n_library_of_exile
    n_mmorpg["mmorpg"]
    n_playeranimator["playeranimator"]
    n_mmorpg -->|depende| n_playeranimator
    n_mmorpg["mmorpg"]
    n_playeranimator["playeranimator"]
    n_mmorpg -->|depende| n_playeranimator
    n_mmorpg["mmorpg"]
    n_playeranimator["playeranimator"]
    n_mmorpg -->|depende| n_playeranimator
    n_mmorpg["mmorpg"]
    n_the_harvest["the_harvest"]
    n_mmorpg -->|depende| n_the_harvest
    n_mmorpg["mmorpg"]
    n_the_harvest["the_harvest"]
    n_mmorpg -->|depende| n_the_harvest
    n_mmorpg["mmorpg"]
    n_the_harvest["the_harvest"]
    n_mmorpg -->|depende| n_the_harvest
    n_mns["mns"]
    n_moogs_structures["moogs_structures"]
    n_mns -->|depende| n_moogs_structures
    n_mns["mns"]
    n_moogs_structures["moogs_structures"]
    n_mns -->|depende| n_moogs_structures
    n_mns_compat["mns_compat"]
    n_mmorpg["mmorpg"]
    n_mns_compat -->|depende| n_mmorpg
    n_mns_compat["mns_compat"]
    n_mmorpg["mmorpg"]
    n_mns_compat -->|depende| n_mmorpg
    n_mns_compat["mns_compat"]
    n_mmorpg["mmorpg"]
    n_mns_compat -->|depende| n_mmorpg
    n_mowziesmobs["mowziesmobs"]
    n_geckolib["geckolib"]
    n_mowziesmobs -->|depende| n_geckolib
    n_mowziesmobs["mowziesmobs"]
    n_geckolib["geckolib"]
    n_mowziesmobs -->|depende| n_geckolib
    n_noworldgenwarning["noworldgenwarning"]
    n_mixin_booster["mixin_booster"]
    n_noworldgenwarning -->|depende| n_mixin_booster
    n_noworldgenwarning["noworldgenwarning"]
    n_mixin_booster["mixin_booster"]
    n_noworldgenwarning -->|depende| n_mixin_booster
    n_p1nero_bow["p1nero_bow"]
    n_epicfight["epicfight"]
    n_p1nero_bow -->|depende| n_epicfight
    n_p1nero_bow["p1nero_bow"]
    n_epicfight["epicfight"]
    n_p1nero_bow -->|depende| n_epicfight
    n_p1nero_ec["p1nero_ec"]
    n_cataclysm["cataclysm"]
    n_p1nero_ec -->|depende| n_cataclysm
    n_p1nero_ec["p1nero_ec"]
    n_cataclysm["cataclysm"]
    n_p1nero_ec -->|depende| n_cataclysm
    n_p1nero_ec["p1nero_ec"]
    n_efn["efn"]
    n_p1nero_ec -->|depende| n_efn
    n_p1nero_ec["p1nero_ec"]
    n_efn["efn"]
    n_p1nero_ec -->|depende| n_efn
    n_puzzleslib["puzzleslib"]
    n_puzzlesaccessapi["puzzlesaccessapi"]
    n_puzzleslib -->|depende| n_puzzlesaccessapi
    n_puzzleslib["puzzleslib"]
    n_puzzlesaccessapi["puzzlesaccessapi"]
    n_puzzleslib -->|depende| n_puzzlesaccessapi
    n_puzzleslib["puzzleslib"]
    n_puzzlesaccessapi["puzzlesaccessapi"]
    n_puzzleslib -->|depende| n_puzzlesaccessapi
    n_rpg_origins["rpg_origins"]
    n_origins["origins"]
    n_rpg_origins -->|depende| n_origins
    n_simplyswords["simplyswords"]
    n_architectury["architectury"]
    n_simplyswords -->|depende| n_architectury
    n_simplyswords["simplyswords"]
    n_cloth_config["cloth_config"]
    n_simplyswords -->|depende| n_cloth_config
    n_structure_layout_optimizer["structure_layout_optimizer"]
    n_resourcefulconfig["resourcefulconfig"]
    n_structure_layout_optimizer -->|depende| n_resourcefulconfig
    n_structure_layout_optimizer["structure_layout_optimizer"]
    n_resourcefulconfig["resourcefulconfig"]
    n_structure_layout_optimizer -->|depende| n_resourcefulconfig
    n_super_golem["super_golem"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_golem -->|depende| n_epic_fight_avalon
    n_super_golem["super_golem"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_golem -->|depende| n_epic_fight_avalon
    n_super_golem["super_golem"]
    n_epicfight["epicfight"]
    n_super_golem -->|depende| n_epicfight
    n_super_golem["super_golem"]
    n_epicfight["epicfight"]
    n_super_golem -->|depende| n_epicfight
    n_super_warden["super_warden"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_warden -->|depende| n_epic_fight_avalon
    n_super_warden["super_warden"]
    n_epic_fight_avalon["epic_fight_avalon"]
    n_super_warden -->|depende| n_epic_fight_avalon
    n_super_warden["super_warden"]
    n_epicfight["epicfight"]
    n_super_warden -->|depende| n_epicfight
    n_super_warden["super_warden"]
    n_epicfight["epicfight"]
    n_super_warden -->|depende| n_epicfight
    n_swem["swem"]
    n_geckolib["geckolib"]
    n_swem -->|depende| n_geckolib
    n_swem["swem"]
    n_geckolib["geckolib"]
    n_swem -->|depende| n_geckolib
    n_swem["swem"]
    n_playeranimator["playeranimator"]
    n_swem -->|depende| n_playeranimator
    n_swem["swem"]
    n_playeranimator["playeranimator"]
    n_swem -->|depende| n_playeranimator
    n_sword_soaring["sword_soaring"]
    n_epicfight["epicfight"]
    n_sword_soaring -->|depende| n_epicfight
    n_sword_soaring["sword_soaring"]
    n_epicfight["epicfight"]
    n_sword_soaring -->|depende| n_epicfight
    n_sword_soaring["sword_soaring"]
    n_invincible["invincible"]
    n_sword_soaring -->|depende| n_invincible
    n_sword_soaring["sword_soaring"]
    n_invincible["invincible"]
    n_sword_soaring -->|depende| n_invincible
    n_t_and_t["t_and_t"]
    n_cristellib["cristellib"]
    n_t_and_t -->|depende| n_cristellib
    n_t_and_t["t_and_t"]
    n_cristellib["cristellib"]
    n_t_and_t -->|depende| n_cristellib
    n_taxfreelevels["taxfreelevels"]
    n_cloth_config["cloth_config"]
    n_taxfreelevels -->|depende| n_cloth_config
    n_taxfreelevels["taxfreelevels"]
    n_cloth_config["cloth_config"]
    n_taxfreelevels -->|depende| n_cloth_config
    n_tcr_bosses["tcr_bosses"]
    n_ba_bt["ba_bt"]
    n_tcr_bosses -->|depende| n_ba_bt
    n_tcr_bosses["tcr_bosses"]
    n_ba_bt["ba_bt"]
    n_tcr_bosses -->|depende| n_ba_bt
    n_tcr_bosses["tcr_bosses"]
    n_efn["efn"]
    n_tcr_bosses -->|depende| n_efn
    n_tcr_bosses["tcr_bosses"]
    n_efn["efn"]
    n_tcr_bosses -->|depende| n_efn
    n_tcr_bosses["tcr_bosses"]
    n_epicfight["epicfight"]
    n_tcr_bosses -->|depende| n_epicfight
    n_tcr_bosses["tcr_bosses"]
    n_epicfight["epicfight"]
    n_tcr_bosses -->|depende| n_epicfight
    n_tcrcore["tcrcore"]
    n_ba_bt["ba_bt"]
    n_tcrcore -->|depende| n_ba_bt
    n_tcrcore["tcrcore"]
    n_ba_bt["ba_bt"]
    n_tcrcore -->|depende| n_ba_bt
    n_tcrcore["tcrcore"]
    n_combat_evolution["combat_evolution"]
    n_tcrcore -->|depende| n_combat_evolution
    n_tcrcore["tcrcore"]
    n_combat_evolution["combat_evolution"]
    n_tcrcore -->|depende| n_combat_evolution
    n_tcrcore["tcrcore"]
    n_dodge_parry_reward["dodge_parry_reward"]
    n_tcrcore -->|depende| n_dodge_parry_reward
    n_tcrcore["tcrcore"]
    n_dodge_parry_reward["dodge_parry_reward"]
    n_tcrcore -->|depende| n_dodge_parry_reward
    n_tcrcore["tcrcore"]
    n_efn["efn"]
    n_tcrcore -->|depende| n_efn
