import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, it } from 'node:test';

import {
  createForgeArgsFileProcessPlan,
  forgeArgsFileName,
  type ProcessExit,
  type SpawnedProcess,
} from '@voidfall/minecraft-process';

import {
  Sandbox,
  SandboxError,
  createProcessSandboxBootRunner,
  runRestoredWorldBoot,
  type SandboxBootRunner,
} from '../src/index.js';

/**
 * Sandbox composition against real temporary directories.
 *
 * No JVM is started: the boot runner is an interface, and a test that spawned
 * one would be testing the runner instead of the composition — and could not
 * arrange a boot that times out or writes a file on its first run.
 */

const roots: string[] = [];

afterEach(async () => {
  while (roots.length > 0) {
    const root = roots.pop();
    if (root !== undefined) await rm(root, { recursive: true, force: true });
  }
});

async function fixture() {
  const base = await mkdtemp(join(tmpdir(), 'voidfall-sandbox-test-'));
  roots.push(base);
  const workspaceRoot = join(base, 'workspace');
  const parentDirectory = join(base, 'sandboxes');
  await mkdir(join(workspaceRoot, 'mods'), { recursive: true });
  await mkdir(join(workspaceRoot, 'config'), { recursive: true });
  await mkdir(join(workspaceRoot, 'world'), { recursive: true });
  await mkdir(parentDirectory, { recursive: true });

  await writeFile(join(workspaceRoot, 'mods', 'alpha.jar'), 'not really a jar');
  await writeFile(join(workspaceRoot, 'config', 'alpha.toml'), 'enabled = true\n');
  // The thing that must never be copied.
  await writeFile(join(workspaceRoot, 'world', 'level.dat'), 'precious');

  return { base, workspaceRoot, parentDirectory };
}

/** A runner that reports an outcome and can write files, the way a boot does. */
function scriptedRunner(
  outcome: 'booted' | 'timed-out' | 'exited-early' | 'failed-to-start',
  generates: ReadonlyMap<string, string> = new Map(),
): SandboxBootRunner {
  return {
    async boot({ sandboxRoot }) {
      for (const [relativePath, content] of generates) {
        const target = join(sandboxRoot, ...relativePath.split('/'));
        await mkdir(join(target, '..'), { recursive: true });
        await writeFile(target, content, 'utf8');
      }
      return { outcome, tail: ['[Server] Starting...', `[Server] ${outcome}`] };
    },
  };
}

const FILES = [
  { path: 'mods/alpha.jar', role: 'mod-archive' as const },
  { path: 'config/alpha.toml', role: 'configuration' as const },
];

describe('composing a sandbox', () => {
  it('brings in what was named and nothing else', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    const entries = (await readdir(composed.root)).sort();
    // The world is absent. Not copied, not linked, not referenced — a boot test
    // that could corrupt somebody's world is the accident it exists to prevent.
    assert.deepEqual(entries, ['config', 'eula.txt', 'mods', 'server.properties']);
    assert.equal(
      await readFile(join(composed.root, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });

  it('boots into a fresh level, never the operator name', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    const properties = await readFile(join(composed.root, 'server.properties'), 'utf8');
    assert.match(properties, /level-name=voidfall-sandbox-world/u);
    // Loopback and closed. A sandbox that let somebody in would be a server.
    assert.match(properties, /server-ip=127\.0\.0\.1/u);
    assert.match(properties, /max-players=0/u);
    assert.match(properties, /enable-rcon=false/u);
    // Written fresh, not copied: the real one holds a port, a seed and an RCON
    // password, and none of them belong in a throwaway directory.
    assert.match(properties, /Generated by VoidFall/u);
  });

  it('refuses to accept the EULA on the operator behalf', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: FILES,
        eulaAccepted: false,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'eula-not-accepted',
    );
    // Not inferred from "they asked for a boot" either.
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: FILES,
        eulaAccepted: undefined as unknown as boolean,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'eula-not-accepted',
    );
  });

  it('uses staged content instead of what is installed', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      stagedFiles: new Map([['config/alpha.toml', 'enabled = false\n']]),
      eulaAccepted: true,
      serverPort: 25_999,
    });

    // The whole reason to boot at all: test the change, not what is already
    // installed.
    assert.equal(
      await readFile(join(composed.root, 'config', 'alpha.toml'), 'utf8'),
      'enabled = false\n',
    );
    // And the workspace still holds the original.
    assert.equal(
      await readFile(join(workspaceRoot, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });

  it('refuses a path that would escape either root', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: [{ path: '../outside.jar', role: 'mod-archive' }],
        eulaAccepted: true,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'unsafe-path',
    );
  });

  it('refuses to build itself inside the workspace it copies from', async () => {
    const { workspaceRoot } = await fixture();
    const inside = join(workspaceRoot, 'sandboxes');
    await mkdir(inside, { recursive: true });
    const sandbox = new Sandbox({ parentDirectory: inside, runner: scriptedRunner('booted') });
    // It would be scanned by the next import, and deleting it would delete part
    // of what it was copied from.
    await assert.rejects(
      sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 }),
      (error: unknown) =>
        error instanceof SandboxError && error.code === 'sandbox-root-inside-workspace',
    );
  });

  it('names a source it could not find rather than booting without it', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: [{ path: 'mods/missing.jar', role: 'mod-archive' }],
        eulaAccepted: true,
        serverPort: 25_999,
      }),
      (error: unknown) =>
        error instanceof SandboxError &&
        error.code === 'source-missing' &&
        error.path === 'mods/missing.jar',
    );
  });
});

describe('booting a sandbox', () => {
  it('reports the files that only exist because it ran', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({
      parentDirectory,
      runner: scriptedRunner(
        'booted',
        new Map([['config/delta-common.toml', '#Range: 0 ~ 10\nvalue = 5\n']]),
      ),
    });
    await sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 });

    const report = await sandbox.boot({ timeoutMs: 1_000 });
    assert.equal(report.outcome, 'booted');
    // This is the payoff. A mod classified RUNTIME_ONLY because nothing was on
    // disk writes its file the first time it runs, and it turns up here.
    assert.deepEqual(report.generatedFiles, ['config/delta-common.toml']);
    await sandbox.dispose();
  });

  it('keeps a timeout as its own answer rather than calling it a failure', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('timed-out') });
    await sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 });

    const report = await sandbox.boot({ timeoutMs: 1_000 });
    // The server may simply have been slow. "Did not finish inside the window"
    // is a fact; "failed" would not be.
    assert.equal(report.outcome, 'timed-out');
    assert.deepEqual(report.generatedFiles, []);
    assert.ok(report.tail.length > 0);
  });

  it('refuses to boot something that was never composed', async () => {
    const { parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.boot({ timeoutMs: 1_000 }),
      (error: unknown) => error instanceof SandboxError && error.code === 'not-composed',
    );
  });
});

describe('disposal', () => {
  it('removes the sandbox and is safe to call twice', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    await sandbox.dispose();
    // Cleanup that throws when there is nothing to clean is cleanup people
    // stop calling.
    await sandbox.dispose();

    assert.equal(await readdir(composed.root).catch(() => undefined), undefined);
    // And the workspace is exactly as it was.
    assert.equal(await readFile(join(workspaceRoot, 'world', 'level.dat'), 'utf8'), 'precious');
    assert.equal(
      await readFile(join(workspaceRoot, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });
});

describe('booting an isolated restored world', () => {
  it('builds the Forge runtime around the restored copy and never changes the active world', async () => {
    const { base, workspaceRoot } = await fixture();
    const restoredRoot = join(base, 'restored-server');
    await mkdir(join(restoredRoot, 'world'), { recursive: true });
    await writeFile(join(restoredRoot, 'world', 'level.dat'), 'restored-world');
    await writeFile(join(workspaceRoot, 'eula.txt'), 'eula=true\n');
    await writeFile(
      join(workspaceRoot, 'server.properties'),
      'server-ip=0.0.0.0\nserver-port=25565\nenable-rcon=true\nrcon.password=secret\n',
    );

    let bootRoot: string | undefined;
    const runner: SandboxBootRunner = {
      async boot({ sandboxRoot }) {
        bootRoot = sandboxRoot;
        return { outcome: 'booted', tail: ['Done (12.0s)!'] };
      },
    };
    const evidence = await runRestoredWorldBoot({
      workspaceRoot,
      activeWorldRoot: join(workspaceRoot, 'world'),
      restoredRoot,
      java: {
        executable: '/opt/java/bin/java',
        major: 17,
        version: '17.0.12',
        source: 'PATH',
      },
      argsFile: 'libraries/net/minecraftforge/forge/1.20.1-47.4.4/unix_args.txt',
      runner,
    });

    assert.equal(bootRoot, restoredRoot);
    assert.equal(evidence.report.outcome, 'booted');
    assert.equal(await readFile(join(restoredRoot, 'world', 'level.dat'), 'utf8'), 'restored-world');
    assert.equal(await readFile(join(workspaceRoot, 'world', 'level.dat'), 'utf8'), 'precious');
    assert.equal(await readFile(join(restoredRoot, 'config', 'alpha.toml'), 'utf8'), 'enabled = true\n');
    assert.equal(await readFile(join(restoredRoot, 'mods', 'alpha.jar'), 'utf8'), 'not really a jar');
    const properties = await readFile(join(restoredRoot, 'server.properties'), 'utf8');
    assert.match(properties, /server-ip=127\.0\.0\.1/u);
    assert.match(properties, /level-name=world/u);
    assert.match(properties, /max-players=0/u);
    assert.match(properties, /enable-rcon=false/u);
    assert.doesNotMatch(properties, /rcon\.password/u);
  });

  it('refuses an overlapping root and any runtime collision', async () => {
    const { base, workspaceRoot } = await fixture();
    await writeFile(join(workspaceRoot, 'eula.txt'), 'eula=true\n');
    await assert.rejects(
      runRestoredWorldBoot({
        workspaceRoot,
        activeWorldRoot: join(workspaceRoot, 'world'),
        restoredRoot: join(workspaceRoot, 'restore'),
      }),
      (error: unknown) =>
        error instanceof SandboxError && error.code === 'restore-root-overlaps-workspace',
    );

    const restoredRoot = join(base, 'restored-conflict');
    await mkdir(join(restoredRoot, 'world'), { recursive: true });
    await mkdir(join(restoredRoot, 'config'), { recursive: true });
    await writeFile(join(restoredRoot, 'world', 'level.dat'), 'restored-world');
    await writeFile(join(restoredRoot, 'config', 'alpha.toml'), 'unexpected collision');
    await assert.rejects(
      runRestoredWorldBoot({
        workspaceRoot,
        activeWorldRoot: join(workspaceRoot, 'world'),
        restoredRoot,
        java: {
          executable: '/opt/java/bin/java',
          major: 17,
          version: '17.0.12',
          source: 'PATH',
        },
        argsFile: 'libraries/net/minecraftforge/forge/1.20.1-47.4.4/unix_args.txt',
        runner: scriptedRunner('booted'),
      }),
      (error: unknown) =>
        error instanceof SandboxError &&
        error.code === 'destination-conflict' &&
        error.path === 'config/alpha.toml',
    );
  });
});

describe('the runner that actually starts a JVM', () => {
  /** A process handle that behaves the way a spawned server does. */
  class ScriptedProcess implements SpawnedProcess {
    public readonly pid = 4_242;
    public gracefulStops = 0;
    public forcedTerminations = 0;
    #exit: ProcessExit | undefined;
    #stdout = '';

    public constructor(
      private readonly script: {
        readonly stdoutAfterPolls?: ReadonlyMap<number, string>;
        readonly exitAfterPolls?: number;
        readonly ignoresGracefulStop?: boolean;
        readonly ignoresForcedTermination?: boolean;
      } = {},
    ) {}

    #polls = 0;

    getExit(): ProcessExit | undefined {
      return this.#exit;
    }

    readOutput() {
      this.#polls += 1;
      const line = this.script.stdoutAfterPolls?.get(this.#polls);
      if (line !== undefined) this.#stdout += `${line}\n`;
      if (this.script.exitAfterPolls === this.#polls) {
        this.#exit = { code: 1, signal: null, exitedAt: '2026-08-07T12:00:00.000Z' };
      }
      return {
        stdout: this.#stdout,
        stderr: '',
        stdoutTruncated: false,
        stderrTruncated: false,
      };
    }

    async requestConsoleCommand(): Promise<void> {}

    async requestGracefulStop(): Promise<void> {
      this.gracefulStops += 1;
      if (this.script.ignoresGracefulStop !== true) {
        this.#exit = { code: 0, signal: null, exitedAt: '2026-08-07T12:00:01.000Z' };
      }
    }

    async forceTerminate(): Promise<void> {
      this.forcedTerminations += 1;
      if (this.script.ignoresForcedTermination !== true) {
        this.#exit = { code: 137, signal: 'SIGKILL', exitedAt: '2026-08-07T12:00:02.000Z' };
      }
    }

    async waitForExit(): Promise<ProcessExit | undefined> {
      return this.#exit;
    }
  }

  function runnerFor(handle: SpawnedProcess, spawnFails = false) {
    let now = 0;
    return createProcessSandboxBootRunner({
      // A leading slash is absolute on both platforms, so the fixture needs no
      // backslashes — one fewer thing an escape can quietly break.
      javaExecutable: '/opt/java/bin/java',
      launch: {
        kind: 'forge-args-file' as const,
        argsFile: 'libraries/net/minecraftforge/forge/1.20.1-47.4.4/unix_args.txt',
      },
      initialMemoryMiB: 1_024,
      maximumMemoryMiB: 2_048,
      runtime: {
        async spawn() {
          if (spawnFails) throw new Error('no java here');
          return handle;
        },
      },
      pollIntervalMs: 1,
      clock: () => now,
      sleep: async () => {
        now += 1_000;
      },
    });
  }

  it('waits for the same line the process adapter waits for', async () => {
    const handle = new ScriptedProcess({
      stdoutAfterPolls: new Map([
        [1, '[Server] Loading...'],
        [3, '[Server thread/INFO]: Done (21.5s)! For help, type "help"'],
      ]),
    });
    const report = await runnerFor(handle).boot({ sandboxRoot: '/tmp/sbx', timeoutMs: 60_000 });

    assert.equal(report.outcome, 'booted');
    assert.ok(report.tail.some((line) => line.includes('Done (21.5s)')));
    // Even a successful boot does not leave the process running: the caller's
    // next move is deleting the directory it has open.
    assert.equal(handle.gracefulStops, 1);
    assert.equal(handle.getExit()?.code, 0);
  });

  it('ends a process that ignores the polite request', async () => {
    const handle = new ScriptedProcess({ ignoresGracefulStop: true });
    const report = await runnerFor(handle).boot({ sandboxRoot: '/tmp/sbx', timeoutMs: 3_000 });

    assert.equal(report.outcome, 'timed-out');
    // Asked politely first, then not. Leaving it alive would hold a lock on a
    // directory somebody is about to remove and keep a port bound.
    assert.equal(handle.gracefulStops, 1);
    assert.equal(handle.forcedTerminations, 1);
    assert.notEqual(handle.getExit(), undefined);
  });

  it('surfaces a JVM that survives both stop attempts', async () => {
    const handle = new ScriptedProcess({
      ignoresGracefulStop: true,
      ignoresForcedTermination: true,
    });
    await assert.rejects(
      runnerFor(handle).boot({ sandboxRoot: '/tmp/sbx', timeoutMs: 1_000 }),
      (error: unknown) =>
        error instanceof SandboxError && error.code === 'process-still-running',
    );
    assert.equal(handle.gracefulStops, 1);
    assert.equal(handle.forcedTerminations, 1);
  });

  it('tells an early exit apart from a slow start', async () => {
    const handle = new ScriptedProcess({
      stdoutAfterPolls: new Map([[1, '[Server] Loading...']]),
      exitAfterPolls: 2,
    });
    const report = await runnerFor(handle).boot({ sandboxRoot: '/tmp/sbx', timeoutMs: 60_000 });
    // Two different facts. Folding them together would tell an operator to wait
    // longer for a server that already gave up.
    assert.equal(report.outcome, 'exited-early');
    assert.ok(report.tail.length > 0);
  });

  it('reports a spawn it could not even attempt', async () => {
    const report = await runnerFor(new ScriptedProcess(), true).boot({
      sandboxRoot: '/tmp/sbx',
      timeoutMs: 1_000,
    });
    assert.equal(report.outcome, 'failed-to-start');
    assert.deepEqual(report.tail, ['no java here']);
  });

  it('refuses a launch plan it cannot build rather than spawning something else', async () => {
    const runner = createProcessSandboxBootRunner({
      javaExecutable: 'java',
      launch: { kind: 'jar', serverJar: '../../etc/payload.jar' },
      initialMemoryMiB: 1_024,
      maximumMemoryMiB: 2_048,
      runtime: {
        async spawn() {
          throw new Error('must not be reached');
        },
      },
    });
    const report = await runner.boot({ sandboxRoot: '/tmp/sbx', timeoutMs: 1_000 });
    // A relative java binary and a JAR named with a path are both refused by
    // the shared launch plan, which is the point of building one at all.
    assert.equal(report.outcome, 'failed-to-start');
  });
});

describe('the launcher a modern Forge server actually needs', () => {
  it('builds the args-file command rather than a -jar one', () => {
    const plan = createForgeArgsFileProcessPlan({
      platform: 'linux',
      javaExecutable: '/opt/java/bin/java',
      serverDirectory: '/srv/sandbox',
      argsFile: 'libraries/net/minecraftforge/forge/1.20.1-47.4.4/unix_args.txt',
      initialMemoryMiB: 1_024,
      maximumMemoryMiB: 4_096,
    });
    // Forge 1.20.1 ships no fat jar. Its own run.sh is
    //   java @user_jvm_args.txt @libraries/.../unix_args.txt nogui
    // so a plan built with -jar cannot start it at all.
    assert.deepEqual([...plan.args], [
      '-Xms1024M',
      '-Xmx4096M',
      '-Dfile.encoding=UTF-8',
      '@libraries/net/minecraftforge/forge/1.20.1-47.4.4/unix_args.txt',
      'nogui',
    ]);
    assert.equal(plan.cwd, '/srv/sandbox');
  });

  it('names the args file per platform, which is the only difference', () => {
    assert.equal(forgeArgsFileName('linux'), 'unix_args.txt');
    assert.equal(forgeArgsFileName('win32'), 'win_args.txt');
  });

  it('refuses an args file that points outside the tree being launched', () => {
    const base = {
      platform: 'linux' as const,
      javaExecutable: '/opt/java/bin/java',
      serverDirectory: '/srv/sandbox',
      initialMemoryMiB: 1_024,
      maximumMemoryMiB: 4_096,
    };
    for (const argsFile of [
      '../elsewhere/unix_args.txt',
      '/etc/unix_args.txt',
      'libraries/../../unix_args.txt',
      'libraries/forge/run.sh',
    ]) {
      // A traversal here would hand the JVM arguments from outside the
      // directory, which is the one thing a sandbox must not do.
      assert.throws(() => createForgeArgsFileProcessPlan({ ...base, argsFile }), Error, argsFile);
    }
  });
});
