import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, it } from 'node:test';

import { Sandbox, SandboxError, type SandboxBootRunner } from '../src/index.js';

/**
 * Sandbox composition against real temporary directories.
 *
 * No JVM is started: the boot runner is an interface, and a test that spawned
 * one would be testing the runner instead of the composition — and could not
 * arrange a boot that times out or writes a file on its first run.
 */

const roots: string[] = [];

afterEach(async () => {
  while (roots.length > 0) {
    const root = roots.pop();
    if (root !== undefined) await rm(root, { recursive: true, force: true });
  }
});

async function fixture() {
  const base = await mkdtemp(join(tmpdir(), 'voidfall-sandbox-test-'));
  roots.push(base);
  const workspaceRoot = join(base, 'workspace');
  const parentDirectory = join(base, 'sandboxes');
  await mkdir(join(workspaceRoot, 'mods'), { recursive: true });
  await mkdir(join(workspaceRoot, 'config'), { recursive: true });
  await mkdir(join(workspaceRoot, 'world'), { recursive: true });
  await mkdir(parentDirectory, { recursive: true });

  await writeFile(join(workspaceRoot, 'mods', 'alpha.jar'), 'not really a jar');
  await writeFile(join(workspaceRoot, 'config', 'alpha.toml'), 'enabled = true\n');
  // The thing that must never be copied.
  await writeFile(join(workspaceRoot, 'world', 'level.dat'), 'precious');

  return { base, workspaceRoot, parentDirectory };
}

/** A runner that reports an outcome and can write files, the way a boot does. */
function scriptedRunner(
  outcome: 'booted' | 'timed-out' | 'exited-early' | 'failed-to-start',
  generates: ReadonlyMap<string, string> = new Map(),
): SandboxBootRunner {
  return {
    async boot({ sandboxRoot }) {
      for (const [relativePath, content] of generates) {
        const target = join(sandboxRoot, ...relativePath.split('/'));
        await mkdir(join(target, '..'), { recursive: true });
        await writeFile(target, content, 'utf8');
      }
      return { outcome, tail: ['[Server] Starting...', `[Server] ${outcome}`] };
    },
  };
}

const FILES = [
  { path: 'mods/alpha.jar', role: 'mod-archive' as const },
  { path: 'config/alpha.toml', role: 'configuration' as const },
];

describe('composing a sandbox', () => {
  it('brings in what was named and nothing else', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    const entries = (await readdir(composed.root)).sort();
    // The world is absent. Not copied, not linked, not referenced — a boot test
    // that could corrupt somebody's world is the accident it exists to prevent.
    assert.deepEqual(entries, ['config', 'eula.txt', 'mods', 'server.properties']);
    assert.equal(
      await readFile(join(composed.root, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });

  it('boots into a fresh level, never the operator name', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    const properties = await readFile(join(composed.root, 'server.properties'), 'utf8');
    assert.match(properties, /level-name=voidfall-sandbox-world/u);
    // Loopback and closed. A sandbox that let somebody in would be a server.
    assert.match(properties, /server-ip=127\.0\.0\.1/u);
    assert.match(properties, /max-players=0/u);
    assert.match(properties, /enable-rcon=false/u);
    // Written fresh, not copied: the real one holds a port, a seed and an RCON
    // password, and none of them belong in a throwaway directory.
    assert.match(properties, /Generated by VoidFall/u);
  });

  it('refuses to accept the EULA on the operator behalf', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: FILES,
        eulaAccepted: false,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'eula-not-accepted',
    );
    // Not inferred from "they asked for a boot" either.
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: FILES,
        eulaAccepted: undefined as unknown as boolean,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'eula-not-accepted',
    );
  });

  it('uses staged content instead of what is installed', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      stagedFiles: new Map([['config/alpha.toml', 'enabled = false\n']]),
      eulaAccepted: true,
      serverPort: 25_999,
    });

    // The whole reason to boot at all: test the change, not what is already
    // installed.
    assert.equal(
      await readFile(join(composed.root, 'config', 'alpha.toml'), 'utf8'),
      'enabled = false\n',
    );
    // And the workspace still holds the original.
    assert.equal(
      await readFile(join(workspaceRoot, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });

  it('refuses a path that would escape either root', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: [{ path: '../outside.jar', role: 'mod-archive' }],
        eulaAccepted: true,
        serverPort: 25_999,
      }),
      (error: unknown) => error instanceof SandboxError && error.code === 'unsafe-path',
    );
  });

  it('refuses to build itself inside the workspace it copies from', async () => {
    const { workspaceRoot } = await fixture();
    const inside = join(workspaceRoot, 'sandboxes');
    await mkdir(inside, { recursive: true });
    const sandbox = new Sandbox({ parentDirectory: inside, runner: scriptedRunner('booted') });
    // It would be scanned by the next import, and deleting it would delete part
    // of what it was copied from.
    await assert.rejects(
      sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 }),
      (error: unknown) =>
        error instanceof SandboxError && error.code === 'sandbox-root-inside-workspace',
    );
  });

  it('names a source it could not find rather than booting without it', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.compose({
        workspaceRoot,
        files: [{ path: 'mods/missing.jar', role: 'mod-archive' }],
        eulaAccepted: true,
        serverPort: 25_999,
      }),
      (error: unknown) =>
        error instanceof SandboxError &&
        error.code === 'source-missing' &&
        error.path === 'mods/missing.jar',
    );
  });
});

describe('booting a sandbox', () => {
  it('reports the files that only exist because it ran', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({
      parentDirectory,
      runner: scriptedRunner(
        'booted',
        new Map([['config/delta-common.toml', '#Range: 0 ~ 10\nvalue = 5\n']]),
      ),
    });
    await sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 });

    const report = await sandbox.boot({ timeoutMs: 1_000 });
    assert.equal(report.outcome, 'booted');
    // This is the payoff. A mod classified RUNTIME_ONLY because nothing was on
    // disk writes its file the first time it runs, and it turns up here.
    assert.deepEqual(report.generatedFiles, ['config/delta-common.toml']);
    await sandbox.dispose();
  });

  it('keeps a timeout as its own answer rather than calling it a failure', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('timed-out') });
    await sandbox.compose({ workspaceRoot, files: FILES, eulaAccepted: true, serverPort: 25_999 });

    const report = await sandbox.boot({ timeoutMs: 1_000 });
    // The server may simply have been slow. "Did not finish inside the window"
    // is a fact; "failed" would not be.
    assert.equal(report.outcome, 'timed-out');
    assert.deepEqual(report.generatedFiles, []);
    assert.ok(report.tail.length > 0);
  });

  it('refuses to boot something that was never composed', async () => {
    const { parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    await assert.rejects(
      sandbox.boot({ timeoutMs: 1_000 }),
      (error: unknown) => error instanceof SandboxError && error.code === 'not-composed',
    );
  });
});

describe('disposal', () => {
  it('removes the sandbox and is safe to call twice', async () => {
    const { workspaceRoot, parentDirectory } = await fixture();
    const sandbox = new Sandbox({ parentDirectory, runner: scriptedRunner('booted') });
    const composed = await sandbox.compose({
      workspaceRoot,
      files: FILES,
      eulaAccepted: true,
      serverPort: 25_999,
    });

    await sandbox.dispose();
    // Cleanup that throws when there is nothing to clean is cleanup people
    // stop calling.
    await sandbox.dispose();

    assert.equal(await readdir(composed.root).catch(() => undefined), undefined);
    // And the workspace is exactly as it was.
    assert.equal(await readFile(join(workspaceRoot, 'world', 'level.dat'), 'utf8'), 'precious');
    assert.equal(
      await readFile(join(workspaceRoot, 'config', 'alpha.toml'), 'utf8'),
      'enabled = true\n',
    );
  });
});
